### ISSUE TITLE
Add capability to restore original alignment from OC and OP SAM tags to gridss.ComputeSamTags

### ISSUE THREAD

**Issue by SteveSemick** [PapenfussLab/gridss#101]
Hello GRIDSS authors,

I am currently working with duplicate marked, indel realigned bam files. In one of your example scripts (`example_pipeline.sh`) I read:
```
# DO NOT PERFORM INDEL REALIGNMENT
# Not only does does it significantly increase the FDR of SV calls
# but it strips hard clips and makes the SA and MC tags inconsistent.
```
I was wondering how much worse the FDR of SV calls becomes and whether there a way to best run GRIDSS with indel realigned bam input files? Are there certain parameters or steps I can adjust to improve calling the SVs with indel realigned bams? Thank you in advance for any advice you can provide!

Best,
Steve

**Comment by d-cameron** [comment]
>I was wondering how much worse the FDR of SV calls becomes

Indel realignment improves small indel calling (~2% for GATK IIRC) at the expense of larger events. I don't have any data for recent GRIDSS versions but some benchmarking I did a few years ago indicated somewhere in the region of a +20% FDR on for most SV callers.

>there a way to best run GRIDSS with indel realigned bam input files?

Unless you specified `--noOriginalAlignmentTags`, GATK's IndelRealigner will write the original CIGAR and alignment in the OC and OP SAM tags. Restoring the original alignment is the best way but I don't know of any tools that actually do that. I'll add it to my TODO list.

Note that since IndelRealigner only updates the record itself, both the read mate, and other split reads still refer to the original alignment location. This makes the BAM internally inconsistent and can cause issues for GRIDSS. Whilst most of these just result in minor data inconsistencies, the stripping of all hard clipping from the read alignment means that split reads cannot be assembled correctly.

**Comment by d-cameron** [comment]
Feature request: add capability to restore original alignment from `OC` and `OP` SAM tags. to `gridss.ComputeSamTags`

**Comment by d-cameron** [comment]
Waiting on https://github.com/samtools/hts-specs/pull/193 and GATK changes so I don't have to implement this twice.

**Comment by d-cameron** [comment]
Workaround is to use the new gridss.properties option softclip.realignSplitReads and/or SoftClipsToSplitReads.REALIGN_ENTIRE_READ
