### ISSUE TITLE
What are the differences between VCF tags: ASRP/ASSR and RP/SR 

### ISSUE THREAD

**Issue by ruping** [PapenfussLab/gridss#102]
![image](https://user-images.githubusercontent.com/1150365/33970384-aa313ed6-e027-11e7-90f0-1c0fd322e5af.png)

From the vcf header, it says 
ASRP: Count of read pairs incorporated into any breakpoint assembly
RP: Count of read pairs supporting breakpoint per category

ASSR: Count of split, soft clipped or indel-containing reads incorporated into any breakpoint assemblies
SR: Count of split reads supporting breakpoint per category

I am confused with these definitions. What does "any" and "per category" means? Intuitively, if a breakpoint is true, the number of RP or SR reads used for assembly should be roughly equal to the number of RP or SR reads supporting the breakpoint? However, in the case I show above, they can be very different in numbers. 

Thank you for your help!

Best,
Ruping,

**Comment by d-cameron** [comment]
>What does "any" and "per category" means?

"per category" should probably have been named "per sample". When multiple input files are supplied, GRIDSS reports a total and a breakdown for each. If you have multiple files that are from the same sample (e.g. two different sequencing runs), then the `INPUT_CATEGEORY` can be used to group these together in the VCF output. By default, the category (aka sample name) for each input file is the name of the file itself.

>Intuitively, if a breakpoint is true, the number of RP or SR reads used for assembly should be roughly equal to the number of RP or SR reads supporting the breakpoint? However, in the case I show above, they can be very different in numbers.

As mentioned in the description, ASSR includes soft clipped (SC) reads as well as split reads. Only reads with a sufficient number of mappable bases on both sides of the breakpoint will be aligned as split reads. The remainder will be soft clipped and aligned to only one location. GRIDSS attempts to find alignments for soft-clipped reads and convert them to split reads but aligners around 22-28 base pairs of uniquely mappable sequence before they will return an alignment worth considering. For 100bp reads, this means you would expect ASSR to be around twice SR since only the reads in which the breakpoint occurs in bases ~25-75 can be mapped as split reads.

When the sequence flanking the breakpoint is not uniquely mappable this difference becomes much more marked as there are far fewer SR than SC reads.


For RP vs ASRP, GRIDSS assembles all read pairs not matching the reference. This includes read pairs in which one side is unmapped, as well as read pairs in which the mate maps to a different location (technically, at the time of assembly there is no other location and GRIDSS attempts assembly of all reads pairs that do not support the reference - we refer to this as breakend assembly to differentiate it from the targeted breakpoint assembly done by other callers).


In the extreme case, we have found a true variant using GRIDSS with 0 SR and 0 RP support. One side of the breakpoint was in an ALU element which results in 0 reads being correctly mapped to that side. GRIDSS assembled a 316bp from the uniquely mappable breakend from soft clipped reads, and read pairs where the mate was either unmapped, or mapped incorrectly. Although every 100bp reads not able to be uniquely mapped, the 316bp contig could be correctly mapped to the correct ALU element. I am not aware of any short read variant caller where this would be possible.

**Comment by d-cameron** [comment]
ASSR and ASRP do not have a per category breakdown because all input files are assembled together. No per category assembly is performed. The closest GRIDSS has is a pro-rata per category breakdown of the contribution to the assembly for reads from that category/input file/sample.

**Comment by d-cameron** [comment]
> any breakpoint assembly

Here, "Any" refers to all assemblies that support the breakpoint. Ideally, there would be two assemblies supporting a breakpoint from A to B. Since each loci is independently assembled, there would be an assembly at A (which after assembly is found to support breakpoint to B^), and an assembly at B (which after assembly is found to support breakpoint to A). That is, AS=1 and RAS=1.

If you have a large fragment size and/or insufficient coverage, your breakend assemblies can be fragmented assemblies. If you have a gap then you might have two 120bp assemblies instead of a single 300bp assembly. If this fragmentation happened at A then the A breakend would report AS=2 and the B breakend would report RAS=2.

ASSR and ASRP are aggregated counts across all breakend contigs that support the given breakpoint.


^ Converting a breakend assembly to a breakpoint-supporting read using the same process as we use for converting a SC read to a SR: the bases not matching the reference are realigned. If they may uniquely then we consider the SC read/contig as a SR.

**Comment by d-cameron** [comment]
Finally, for assembly purposes, SR/DP are treated as two independent SC/RPs. If they are assembled at both breakends (which for clean variants they will be), they will be counted as two reads/read pairs when calculating ASSR/ASRP. If you have 3 SRs that are assembled at both breakends, you will have SR=3,ASSR=6.

**Comment by ruping** [comment]
Dear Daniel,

   Many thanks for your kind explanation. These are really helpful. Very cool for the 316bp ALU case. 
I am trying GRIDSS on some whole genome sequencing data, will keep bothering you if I have some other issues or questions.

All the best,
Ruping,

**Comment by d-cameron** [comment]
Not a problem. The user documentation is still a work in progress so getting feedback as to what people are actually confused about helps.

**Comment by ruping** [comment]
Hi Daniel,

  I have a related question. Is it possible to extract the information about the allele frequency of a SV? In other words, is there a way to get the read depth info for the SV? The number of reads supporting the REFerence allele seems to be given, but do you have a suggestion about how to count the total reads supporting the SV?

  Many thanks!

Ruping,

**Comment by d-cameron** [comment]
It depends on how restricted/lenient you want to be in your counting. The simplest variant allele frequency calculations are:
Read VAF=SR/(SR+REF)
Fragment VAF=RP(RP+REFPAIR)

In an ideal world with perfect alignment, these would give you the same result. In reality, these underestimate the true VAF. How much by depends on the aligner, read length, and fragment size distribution.

Other options are:
(SR+BSC)/(SR+BSC+REF) if you're willing to assume all soft clips support that breakpoint (not true for promiscuous breakpoint locations)
(ASSR)/(ASSR+REF) and (ASRP)/(ASRP+REFPAIR) if you're willing to assume that all variant-support reads should be assembled (a reasonable assumption given sufficient coverage).

Unfortunately, which VAF definition is the most accurate changes depending on your data. In my analysis, I've typically taken the average of multiple calculations. For example:(SR+RP)/(SR+RP+REF+REFPAIR).


Note that the VAF can be different for each breakend since the overall ploidy is not necessary the same on both sides A chr1-chr2 fusion can be het on one side and homozyous on the other (e.g. loss of a copy of chr2)

**Comment by WinterLi1993** [comment]
@d-cameron  
my data is produced by  the target panel sequencing  .
what is the better method to calculate VAF ?

**Comment by d-cameron** [comment]
For your very high coverage data, I recommend not using any of the AS* fields in your VAF calculation.

**Comment by WinterLi1993** [comment]
@d-cameron 
as the below , that's the Delly2 result ,and that's true variant in my sample. but  this site can not be found by Gridss .
so something wrong with Gridss  ?
chr6	117642092	BND00018142	C	C[chr1:154142762[	.	PASS	PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr1;END=154142762;PE=1001;MAPQ=60;CT=3to5;CIPOS=-1,1;CIEND=-1,1;INSLEN=0;HOMLEN=0;SR=10;SRQ=1;CONSENSUS=GAGTAAGATTGACTTAAGGCTGACCACGTAACACAAGGCTCTCAAAACTCCAATACATGCCAAGTCACTACCAACTTCCTTTGGTGTACAGAAAAAGAGATT;CE=1.94802;RDRATIO=1.00106;SOMATIC	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	0/1:-1000,0,-1000:10000:PASS:11286:22322:4829:3:3057:1207:3006:1300	0/0:0,-881.513,-1000:10000:PASS:8794:17894:4138:3:3137:1:2931:0
chr6	117642093	BND00018143	T	]chr1:154142761]T	.	PASS	PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr1;END=154142761;PE=860;MAPQ=60;CT=5to3;CIPOS=-1,1;CIEND=-1,1;INSLEN=0;HOMLEN=0;SR=10;SRQ=1;CONSENSUS=AGAGTTTGACCCACTTTGCCTAGCTGTGGCATAGGACAGTGCACATGATATTTCTCCTCTCAAACACTGCCTCCAGGTCAACCAACCATGTTACCATCTATTCT;CE=1.96501;RDRATIO=1.00188;SOMATIC	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	0/1:-1000,0,-1000:10000:PASS:11298:22331:4842:3:3057:865:3009:945	0/0:0,-879.428,-1000:10000:PASS:8811:17899:4150:3:3137:4:2924:0

**Comment by d-cameron** [comment]
Using VCF terminology, there are 2 breakpoints there, each of which contains two breakends. The two breakpoints you have listed (gridss15_1058 and gridss15_2014h) are in different orientations so there is no need to 'choose' either one - they're both there.

The variants you listed indicate that a balanced reciprocal translocation has occurred between chr1 and chr6. In the absence of any other events, this will result in two fusion chromatids. One will contain the start of chr1 connected to the end of chr6, the other will contain the start of chr6 connected to the end of chr1.

I strongly advise you read the VCF file format specifications as the orientation of the brackets (`[` `]`) in the ALT field is extremely important to variant interpretation.

**Comment by d-cameron** [comment]
>but this site can not be found by Gridss

I'm confused. You just linked the variant call made by GRIDSS - why are you saying it isn't found?

**Comment by WinterLi1993** [comment]
@d-cameron  
"but this site can not be found by Gridss" , I means  this site is  filtered by Somaitc.R ,
but is not filtered by Delly2 .

**Comment by d-cameron** [comment]
>`chr6	117642092	BND00018142	C	C[chr1:154142762[	.	PASS PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr1;END=154142762;PE=1001;MAPQ=60;CT=3to5;CIPOS=-1,1;CIEND=-1,1;INSLEN=0;HOMLEN=0;SR=10;SRQ=1;CONSENSUS=GAGTAAGATTGACTTAAGGCTGACCACGTAACACAAGGCTCTCAAAACTCCAATACATGCCAAGTCACTACCAACTTCCTTTGGTGTACAGAAAAAGAGATT;CE=1.94802;RDRATIO=1.00106;SOMATIC	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV 0/1:-1000,0,-1000:10000:PASS:11286:22322:4829:3:3057:1207:3006:1300 0/0:0,-881.513,-1000:10000:PASS:8794:17894:4138:3:3137:1:2931:0`

It should be noted that the DELLY VCF record you linked does not have either PARID or MATEID set and the variants you posted are lacking to records for the other side. I suspect DELLY2 is not not writing BND records in a VCF compliant manner.

**Comment by d-cameron** [comment]
> I means this site is filtered by Somaitc.R

You appear to have (a very low level) of tumour contamination in your normal. Are you aware this was this case?

Somatic.R is not an appropriate script for somatic filtering in your case. Have you looked at tumour/normal QUAL/QUAL plots to gauge the level of contamination you have? The somatic filtering function I posted your other issue is more sophisticated than somatic.R and has a configurable level of allowable normal contamination. This approach is more appropriate.

**Comment by WinterLi1993** [comment]
@d-cameron 
The somatic filtering function ? 
which issue ? sorry ,I do not remember you said about that.

**Comment by WinterLi1993** [comment]
@d-cameron 
sorry ,I can not  find your somatic filtering function you posted ,could you please post again ?
I remember you  post the VAF function .
thank you for help ！

**Comment by d-cameron** [comment]
See #118
