### ISSUE TITLE
SVTYPE field details

### ISSUE THREAD

**Issue by WinterLi1993** [PapenfussLab/gridss#130]
HI,
@d-cameron 
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
I find  there is no any records about  detailed SVTYPE information   in your output VCF  .
my results just only have  'BND' flag  at SVTYPE field  ,,never find any other  flag name .
So  in your VCF , what flags  are included by  SVTYPE    field ??
'BND' ,'DEL' ,'DUP' ,'INV' ,'INS'  ?

**Comment by WinterLi1993** [comment]
deletions are always +-, dups are -+ and inversions are ++ or --.
that's right ?

**Comment by d-cameron** [comment]
GRIDSS uses BND notation for all detected breakpoints. This is intentional a reducing to the simplest corresponding even is not necessarily correct. For example, complex tumour rearrangement will contain deletion-like events in +- orientation but, due to the complex rearrangement pattern, the 'deleted' sequence is not actually deleted, merely rearranged.

**Comment by WinterLi1993** [comment]
@d-cameron 
how to judge DEL ,DEL DUP ,INS ?

**Comment by iprada** [comment]
I have the same problem. I have genotype my sample with gridss and I want to focus first on the deletions. At a first look it is not clear how to get this info from the output vcf

**Comment by d-cameron** [comment]
See https://github.com/PapenfussLab/gridss/issues/74
