### ISSUE TITLE
Are simulation scripts still available?

### ISSUE THREAD

**Issue by teng-gao** [PapenfussLab/gridss#150]
Cannot find src/test/sim directory as stated in the supplementary material

**Comment by d-cameron** [comment]
There's been a bit of repository reorganisation since the paper was published so they're no longer in the latest version of the GRIDSS repository. I set the GRIDSS version number to 1.0 upon publication so you'll find the scripts used to generate the published results in the tag for that version:

https://github.com/PapenfussLab/gridss/tree/v1.0.0/

**Comment by d-cameron** [comment]
We have a more extensive benchmarking publication under review - I'll check with my co-authors as to whether we can get a bioarvix preprint up since it's been over 6 months initial submission.

I do have a public shiny app though: https://shiny.wehi.edu.au/cameron.d/sv_benchmark
