### ISSUE TITLE
Somatic.sh is still an error despite following your instructions.

### ISSUE THREAD

**Issue by FWTT** [PapenfussLab/gridss#157]
> (Too many open files)
> GRIDSS has attempted to open too many files at once and the OS file handle limit has been reached. On linux 'ulimit -n' displays your current limit. This error likely to be encountered if you have specified a large number of input files or threads. The following solution is recommended:
> 
> Increase your OS limit on open file handles (eg ulimit -n _<larger number>_)
> Added -Dgridss.defensiveGC=true to the java command-line used for GRIDSS. Memory mapped file handles are not released to the OS until the buffer is garbage collected . This option add a request forr garbage collection whenever a file handle is no longer used.
> Other options that have solved this problem include:
> 
> Reduce number of worker threads. A large number of input files being processed in parallel results in a large number of files open at the same time.

I have applied both parameter solutions.
While running the Tumor data, I will get an error message "Too many open files" again.
So, I tried to run Tumor and Normal separately, but then I have no problem.

--------------------------------------------------------------------------

1)  I wonder if there are more options to apply differently for running somatic.sh.
2)  I wonder if there is a way to do somatic analysis using the result of analysis of Normal and Tumor separately. 

thanks.

**Comment by d-cameron** [comment]
>I wonder if there is a way to do somatic analysis using the result of analysis of Normal and Tumor separately.

I strongly advise against this. There are significant benefits to joint calling.

>So, I tried to run Tumor and Normal separately, but then I have no problem.

This mean that doubling your ulimit would solve the issue. Note that ulimit changes only apply to the current terminal session. If you've already set your ulimit to the OS hard limit (4096 on many linux system), then you'll need a sysadmin/root to change the hard limit, and possibly a server/systemd restart for the hard limit change to take effect.

>I wonder if there are more options to apply differently for running somatic.sh.

I've updated the documentation to include changing the job chunk size as a resolution to this issue. See https://github.com/PapenfussLab/gridss/commit/52f32f8cbcc22997a415e0aa4e6ae36480bdbefb. A reduced thread count and a larger chunk size should give you good control over the number of file handles open at any one time.

> will get an error message "Too many open files" again.

If you're after a simple solution for a single sample, you can just keep rerunning it until it completes. Rerunning GRIDSS will cause it to continue where it left off. Make sure you have `-Dgridss.gridss.output_to_temp_file=true` set so you don't get data corruption due to partially written intermediate files.

**Comment by FWTT** [comment]
Thank you for your help! 
I'll try it now :)

**Comment by FWTT** [comment]
This works fine!
