### ISSUE TITLE
PositionalAssembler Error and INPUT_NAME_SORT

### ISSUE THREAD

**Issue by tgong1** [PapenfussLab/gridss#164]
Hi,

I recently run GRIDSS1.8.1 with tumor and normal samples.
I found some errors in log file (some shown below), although I got the vcf file successfully.
ERROR	2018-08-17 22:44:13	PositionalAssembler	Error assembling chr5. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. Attempting recovery by resuming assembly at chr5:74034268
ERROR	2018-08-18 00:46:26	PositionalAssembler	Error assembling chr5_GL339449v2_alt. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. Attempting recovery by resuming assembly at chr5_GL339449v2_alt:1493571
au.edu.wehi.idsv.SanityCheckFailureException: Traversal of kmer length 2540 ending at [1487223,1487223] contains an invalid subnode over [1485807-1485812].
ERROR	2018-08-18 01:40:39	PositionalAssembler	Error assembling chr17_GL383563v3_alt. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. Attempting recovery by resuming assembly at chr17_GL383563v3_alt:367114
au.edu.wehi.idsv.SanityCheckFailureException: Traversal of kmer length 2367 ending at [360768,360768] contains an invalid subnode over [359494-359494].

I'd like to know:
Why those happen and how can I avoid those?
Will those errors affect the SV calls, like increased false discovery rate?

Another question about input bam files including multiple-mapping reads:
If I only provide the coordinate-sorted input bam files, how much will it affect the GRIDSS SV calls and why?

If I provide the name sorted input bam files, should I still provide the coordinate-sorted ones, like following?
INPUT="$NORMAL" \
INPUT="$TUMOUR" \
INPUT_NAME_SOTRTED="$NORMAL_NAME_SOTRTED" \
INPUT_NAME_SORTED="$TUMOUR_NAME_SORTED" \

Thank you very much!

**Comment by d-cameron** [comment]
>If I provide the name sorted input bam files, should I still provide the coordinate-sorted ones, like following?

coordinate sorted `INPUT` is always required and `INPUT_NAME_SORTED` is optional. It is only useful for deprecated functionality and I'll being removing it in the next release. I recommend not using `INPUT_NAME_SORTED` at all.

> I found some errors in log file ... Why those happen and how can I avoid those?

The error caused by an internal state inconsistency in the GRIDSS assembler. It's not a user error so there's nothing you can do but it's been really difficult to track down as I haven't been able to get a simple minimum dataset to reproduce the problem so I can properly debug it.

> Will those errors affect the SV calls, like increased false discovery rate?

The effect is limited to GRIDSS not reporting all assemblies immediately (usually ~1-10kb) upstream of the reported recovery position. This is the first time I've seen it reported on something other than in repetitive sequence in an alt contig. If you're able reproduce the issue on a small subset of reads upstream of chr5:74034268 and you are able to privately share the data (looks like human so that might not be possible), I would be very interested in debugging exactly what's going on.

**Comment by tgong1** [comment]
Hi,

Thank you very much for the quick reply.

From Readme.md, you mentioned 
INPUT_NAME_SORTED
Input libraries sorted in lexographical read name order. This parameter is required if any of the input libraries contain multiple alignment records for a single read ("multi-mapping reads"). Failure to supply a name sorted input file for multi-mapping reads will result in an increased false discovery rate.

My input bam files include multi-mapping reads, so I'm wondering how will it affect the SV calling **WITHOUT** INPUT_NAME_SORTED?

Thank you.

**Comment by d-cameron** [comment]
GRIDSS no longer supports aligners that report multiple (non-chimeric) alignments for a single read.

> My input bam files include multi-mapping reads

Having reads that map to multiple locations is not the same as using a multi-mapping aligner. Multi-mapping alignment would require (e.g) running bowtie2 with the `--all` parameter, or something like `-k 100`, or bwa with the `-a` parameter (note that the bwa `-h` parameter reports additional alignments in the `XA` tag so is not actually a multi-mapping reads from the perspective of the SAM specifications).

Are you sure you actually told your aligner to report multiple SAM records for every input read? This is not a very common scenario. The BAM files are huge, and most tools do not support it.

> My input bam files include multi-mapping reads, so I'm wondering how will it affect the SV calling WITHOUT INPUT_NAME_SORTED?

Supplying INPUT_NAME_SORTED no longer has any impact on GRIDSS output.

**Comment by tgong1** [comment]
Thank you Daniel.
I think I misunderstood the "multi-mapping reads". I have reads mapped to multiple positions in genome.
Thank you again for the help.
