### ISSUE TITLE
User Specification of Aligner

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#180]
> GRIDSS invokes an external alignment tool at multiple points during processing. By default this is bwa mem, but can be configured to use bowtie2 or another aligner.

Might there be some instructions provided by the documentation about how to do that?

**Comment by d-cameron** [comment]
This used to be a command-line parameter but it got buried when I refactored the code to be more modular. I've added an example/gridss_separate.sh script that breaks out the various steps that gridss.CallVariants does internally. The script has the `ALIGNER_COMMAND_LINE` argument explicitly set for the first `gridss.SoftClipsToSplitReads` invocation and also has the command line that you would use if running bwa added as a comment.

Note that `gridss.SoftClipsToSplitReads` is run for each input file as well as the assembled contigs so you'll need to change multiple locations if you no longer want to use bwa at all.

Note that:
- the aligner used must output SAM/BAM/CRAM 
- the reference genome must match the reference genome the input files were aligned against
- the output record order of the aligner must match the input order (hence the `--reorder` in bowtie2 since it doesn't do this by default)

My benchmarking indicates that bwa and bowtie2 have equivalent performance but I suspect a different aligner (minimap2?) will perform better for the assembly step as the contigs can be much longer than the input reads. If you find an aligner that does perform considerably better let me know and I can rebenchmark with that aligner and update the GRIDSS default if it looks good.
