### ISSUE TITLE
What is the origin of a '.' in the ALT field

### ISSUE THREAD

**Issue by SdeBlank** [PapenfussLab/gridss#187]
Hi, 
after running joint calling on a tumour and reference sample, a few of the reported SVs showed a '.' followed by a number of bases. It can be both to the left or the right of the sequence. Reading into the vcf specifications, it seems that this is the result of a missing value. Even though the alt position seems to be missing it is still reported with a PASS filter. Could you tell me what results in this specific notation of a breakpoint?

Cheers,
Sam

Example:
1	53263107	gridss5_166331b	A	.TTATAATATGTACTACAA	12465.3	PASS
4	3789930	gridss69_89117b	C	CCTGCCCCTCCTCCTGCTCCTGCCCCTCCTGCCCCTCCTCCTGCTCCTGCCCCTCCTGC.	2034.7	PASS

**Comment by d-cameron** [comment]
A `.` by itself is a missing value, but a `.` with bases before/after is a single breakend. That is, a breakpoint for which the partner location cannot be uniquely specified. These are usually breakpoints into repetitive or non-reference sequence. These are quite useful calls and am using them for viral insertion detection and using them to adjust the start/end positions of copy number blocks.

See [Section 5.4.9 of the VCF specifications](https://samtools.github.io/hts-specs/VCFv4.3.pdf) for details.

**Comment by d-cameron** [comment]
I also use them to report the presence of insertions/gene disruptions. The driver behind their inclusion was a somatic driver gene disruption caused by an exonic SINE element insertion. Although GRIDSS detected both breakends, the fact that the SINE element could not be unique place meant that no breakpoint call was made. With the inclusion of single breakend calls, such insertions are now reported as two single breakends in opposite directions at nearby position (typically within 20bp for SINE/LINE insertions).
