### ISSUE TITLE
Alternate Contig Alignments as Input

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#193]
Could you include a section of recommendations about whether to map to only the standard chromosomes or to include the alternate contigs and use BWA MEM's `bwa-postalt` tool after ordinary alignment?

> Based on feedback from users, a user guide will be produced outlining common workflows, pitfalls, and use cases.

Eagerly anticipating it!

**Comment by d-cameron** [comment]
Running bwa-postalt on the `INPUT` files can make sense if you're interested in alt contigs, but it doesn't make a lot of sense to replace the GRIDSS-internal bwa mem aligner with bwakit. GRIDSS expects that the aligner only perform read alignment. The additional steps in bwakit are not required and some are actively counterproductive. For example, since GRIDSS requests alignment for partial read/contigs so if there are many soft clips with the same sequence (as you would expect for read spanning a breakpoint), duplicate removal would mark all the soft clipped reads of the same length except one as duplicates thus removing their support for the breakpoint.

**Comment by DarioS** [comment]
I suppose that regions which have alternate contigs are not highly conserved within a population and the reference genome is not a good baseline to compare to there, so keeping them out of the analysis might be for the best.
