### ISSUE TITLE
Necessity of MAPQ Filtering of Input BAM

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#209]
I read the FAQ but didn't find an answer, so I would like to ask if it's necessary to filter the BAM file created by bwa mem before I use it for GRIDSS. I notice some strange variants with PASS in the resulting VCF file with lots of nearby reads having MAPQ of 0. For example, the single breakend

```
#CHROM	POS	ID		REF	ALT	QUAL	FILTER
chr1	181660	gridss0_49106b	C	C.	1556.12	PASS
```

actually looks like

![image](https://user-images.githubusercontent.com/631218/56184324-fd091780-605c-11e9-90b0-0d54569ac94f.png)

The true breakpoint looks like it would be somewhere to the left of where GRIDSS positioned it, but it's confusing because this is a 90 times coverage cancer sample but there's a spike of read coverage to the left - almost 1400 reads deep suggesting major misalignment. The solid colour reads typically have a MAPQ of 3 and the pale colour ones have a MAPQ of 0. If I switch to GAPDH, most reads have MAPQ of 60.

A lot of single breakends I looked at don't have any interesting reads nearby the location GRIDSS reports (and are almost always LOW_QUAL). For example,

![image](https://user-images.githubusercontent.com/631218/56184934-49eded80-605f-11e9-9dc7-78598328dcac.png)

Reads not visible in the view are similar to those shown. Might the genomic coordinates in the VCF output be shifted somehow? I notice that the positions of all of the variants I looked at which do **not** have a dot in ALT match exactly to where I'd expect them to be from seeing the region in IGV.

**Comment by d-cameron** [comment]
>I read the FAQ but didn't find an answer, so I would like to ask if it's necessary to filter the BAM file created by bwa mem before I use it for GRIDSS.

Deduplication should be performed but filtering is not necessary.

> chr1	181660	gridss0_49106b	C	C.	1556.12	PASS

Does this variant have the `IMPRECISE` flag set? A default, GRIDSS considers 0.5% of reads in the main fragment size distribution (as defined by the metrics file output by Picard CollectInsertSizeMetrics) to be discordantly mapped. As a result of this, one expects a background rate of FP calls caused nearby reads that just happen to come from unusually large (or small) fragments, and the background rate will increase with coverage.

> read coverage to the left - almost 1400 reads deep

This above variant looks very much like one of these variants. I would expect the `IMPRECISE` flag to be set.

>The true breakpoint looks like it would be somewhere to the left of where GRIDSS positioned it
> Might the genomic coordinates in the VCF output be shifted somehow?

I expect that variant also has a non-zero `CIPOS`. When the call position is ambiguous (due to micro-homology) or imprecise, the chose of nominal position for a variant is arbitrary. `CIPOS` should always be considered when discussing the position of a variant. That said, the above variant is likely to be a false positive.


> A lot of single breakends I looked at don't have any interesting reads nearby the location GRIDSS reports (and are almost always LOW_QUAL). For example,

Single breakend calls have a higher FDR than breakpoints. I generally compensate for this using different QUAL thresholds for breakend and breakpoint calls.

> I notice some strange variants with PASS in the resulting VCF
> this is a 90 times coverage cancer sample

The default GRIDSS filters are not very sophisticated. Over the last year I've worked with the Hartwig Medical Foundation to, amongst other things, develop a somatic GRIDSS post-processing/filtering script. This has not been back-ported into the GRIDSS repository but I strongly advise that you either use that script (if you have matching normal), or adapt those filters for your use.The filter relevant to the above variant is the imprecise filter. At 90x coverage, `IMPRECISE` variants will be almost exclusively false positives (or very low allelic fraction variants).

This scripts can be found at https://github.com/hartwigmedical/scripts/tree/master/gridss
