### ISSUE TITLE
Error with SupportNodeIterator step

### ISSUE THREAD

**Issue by helloeoh001** [PapenfussLab/gridss#216]
Hello,

I ran GRIDSS with a tumor sample, and an error occurred in the step of 'SuuportNodeIterator'
The error message is
 
ERROR   2019-05-29 11:10:36     SupportNodeIterator     Error: kmer in evidence aCbNi63nYcJVC8XUYfhr3HzjW57OWHjy of read M03987:146:000000000-C5W5P:1:1111:9471:14039 (chr1:50837070 139M11S) out of bounds. Kmer support starts at 50836957 which is more than 233 before the breakpoint start position at (1):50837209(50837208-50837211)> (19):45924673(45924672-45924675)>

what would be the problem?
Thanks

**Comment by d-cameron** [comment]
That looks like an internal error in the GRIDSS assembler, possibly due to an out of order input file, or a rare edge case causing a failure. There should be an error message immediately after that message indicating the assembly recovery was performed. The impact is the loss of assembly contigs in the ~5kb immediately before the error position. Workaround available are:
- ignore it as the impact is very localised
- change the assembly chunk size (supply a `CONFIGURATION_FILE=gridss.properties` file that include the line `chunkSize = 5000000`). I've encountered a similar error but it has been extremely difficult to track down as it's only reproducible on the full BAM, and even then it's sensitive to chunk size.
