### ISSUE TITLE
Using site only VCF in create_gridss_pon.R

### ISSUE THREAD

**Issue by Griffan** [PapenfussLab/gridss#228]
Hi, I was directed to this repo after I asked a question about using site-only VCF to create PON files when using gridss script under the pipeline of hartwigmedical. 
https://github.com/hartwigmedical/pipeline5/issues/20

Back to the question, is it possible to create the PON files using this script? or can gridss_somatic_filter.R directly use a site-only PON vcf?

Thanks!

**Comment by d-cameron** [comment]
A site only VCF doesn't make sense in the context of arbitrary breakpoints in BND notation . Breakpoints are defined in terms of location pairs. Where have you generated this site only VCF you refer to? If your site only VCF is in symbolic allele notation (eg `<DEL>`) then the easiest thing to do is it convert this directly to a PON.

To use a PON, GRIDSS requires two file files to exist in the specified PON directory:
- gridss_pon_single_breakend.bed
- gridss_pon_breakpoint.bedpe

The former is a BED PON for single breakends, the latter is a BEDPE pon for breakpoint calls. Site-only symbolic alleles should be converted to BEDPE format for use as a PON. The somatic filtering script uses the score column (which must exist) as the sample count. Since this is by default 1 (gridss.config: `gridss.pon.min_samples = 1`) populating the score field with 1 will work even given the site-only nature of your PON.

**Comment by Griffan** [comment]
I downloaded the PON.vcf.gz file from Hartwig resource site: https://resources.hartwigmedicalfoundation.nl/

**Comment by d-cameron** [comment]
> I downloaded the PON.vcf.gz file from Hartwig resource site: https://resources.hartwigmedicalfoundation.nl/

That's the wrong file. You want HMF-Pipeline-Resources/GRIDSS_PON_3792v1.zip

**Comment by Griffan** [comment]
I assume this is based on hg19/b37(the default setting in GRIDSS script) ? Is it possible that you could also release a version based on hg38? thank you very much!
