### ISSUE TITLE
Enable Use of GnomAD Normals Panel

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#246]
`create_gridss_pon.R` requires a VCF file generated by GRIDSS. Could it be made more general so that I could use GnomAD's [structural variant VCF](https://gnomad.broadinstitute.org/downloads#structural-variants) which is another source of large sample size structural variants of normal samples? Is it feasible?

**Comment by d-cameron** [comment]
There's not really a need for this. A simple conversion from VCF to bedpe would be sufficient and that's covered in the `StructuralVariantAnnotation` vignette. The PON is just a BEDPE file for breakpoints, and a BED file for single breakends.

Having a quick look at the gnomAD VCF, it looks like the StructuralVariantAnnotation package will fail to parse the VCF since the gnomAD does not conform to the VCF specifications. In particular, interchromosomal events are reported with an alt allele of `<BND>` and a non-standard `CHR2` field instead of an actual BND record. This is an issue with gnomAD not complying with the VCF specifications and should either be taken up with them, the records fixed yourself, or filtered.

**Comment by d-cameron** [comment]
It's still supplementing a gnomAD PON with GRIDSS normal samples as they'll capture systematic false positive artefact not captured in the gnomAD call set.
