### ISSUE TITLE
case-control paired data as input 

### ISSUE THREAD

**Issue by a00101** [PapenfussLab/gridss#259]
Dear developers.

I have paired data (tumor-normal).
It doesn't say nothing as to paired.
Let me know how specifying the input data when my data is paired data.

please help.

ddhb.

**Comment by DarioS** [comment]
Somatic analysis is not natively supported by the Java application GRIDSS, but you can use some post-hoc R scripts to reach the somatic variants. You need to run GRIDSS in a loop, each time with a pair of samples. It's best to specify the normal sample first. Then, a Panel of Normals is mandatory. You could create your own if you had lots of patients. There's a create_gridss_pon.R file in the gridss folder of hartwigmedical/scripts/ GitHub repository to process the VCF files for each patient and extract a Panel of Normals. Or, you can get one from the [Hartwig Medical resources website](https://nc.hartwigmedicalfoundation.nl/index.php/s/a8lgLsUrZI5gndd?path=%2FHMFTools-Resources%2FGRIDSS) - if your project uses the reference genome hg19. Otherwise, it's not useful for your analysis and you must create your own Panel of Normals. I have heard that the [Panel of Normals provided by gnomAD](https://gnomad.broadinstitute.org/downloads#structural-variants) is not VCF-compliant, so it won't work with GRIDSS, although a compliant file will be released in the coming months. Next, after you have successfully obtained a relevant Panel of Normals somehow, you can use gridss_somatic_filter.R. Unlike create_gridss_pon.R, gridss_somatic_filter.R is in the GRIDSS repository. So, you need to visit a couple of different GitHub repositories to download all of the necessary R scripts.

The loose R scripts don't belong to any R package which might be installed using a single command (e.g. `install.packages("GRIDSSutils")`) and have the dependencies automatically installed, so, finally, you have to search for `library(` in the R code to identify the package dependencies and install them one by one. Some packages are hosted in CRAN whereas others are hosted in Bioconductor, so the installation commands for the various dependencies will be different.

You will want to set aside an hour or two to set it all up.

**Comment by d-cameron** [comment]
A few clarifications:

- somatic filtering scripts are now included in gridss releases

- paired sample analysis is done by specifying two input files. Specify the
normal as the first bam and the tumor as the second. Gridss is not limited
to two samples and we've successfully done multi-metastasis analysis on 10
tumors from the same patient by feeding gridss all the bams.

- you might want to use the entire gridss purple linx toolkit for somatic
analysis. See https://github.com/hartwigmedical/gridss-purple-linx for
details on how to run it.

**Comment by DarioS** [comment]
Yes, but create_gridss_pon.R isn't part of the releases and might be useful if the asker wants to create their own PON for some reason, so it's worth knowing to look in the Hartwig Medical repository for it.

**Comment by d-cameron** [comment]
> create_gridss_pon.R isn't part of the releases 

It's not part of GRIDSS as it has been replaced by `gridss.GeneratePonBedpe`.
