### ISSUE TITLE
SV type

### ISSUE THREAD

**Issue by woodoo46** [PapenfussLab/gridss#289]
HI gridss developers,

Does gridss report SV type, such as DEL/INS,  in each vcf record?

Thanks

**Comment by CapitanFlint** [comment]
Hi woodoo, i'm not a developer but yes, GRIDSS can do that. As far as i know, it gives 6 categories: 
-INS
-DEL
-DUP (duplications)
-INV (inversions)
-BND (break end points)
-CTX (inter-chromosomal translocations)

In order to obtain them, you need to use the .R script designed to do so, which is stored in this repository.

Hope it helps you.

**Comment by woodoo46** [comment]
Great. Thank!

**Comment by d-cameron** [comment]
Just be aware that the 'simple' SV type does not necessarily correspond to the actual event causing the SV. For example, chromothripsis will result in many deletion-like events in which the 'deleted' region is not actually deleted, merely rearranged.

For further details, see our preprint where we present LINX, a tool that does complex event classification https://www.biorxiv.org/content/10.1101/781013v1 from (somatic) GRIDSS SV calls.
