### ISSUE TITLE
Is there a need for normalization?

### ISSUE THREAD

**Issue by CapitanFlint** [PapenfussLab/gridss#297]
This is not exactly and issue, but i've readed this article: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4481842/ which present and demonstrates that a normalization upon vcf files is needed for accurately representation of the data. Does GRIDSS actually normalize the data? 

Thank you in advance.

**Comment by d-cameron** [comment]
GRIDSS calls all variants in BND notations and centre-aligns any interval of homology or positional imprecision. This is differs from the normalization definition in the linked paper but is more appropriate for SVs since:
a) left-aligning an imprecise variant would result in the nominal position being the least likely position in the interval of possible breakpoint positions
b) depending on the breakend orientation, left-aligning a BND records would force either left or right align it's mate breakend record. It's not possible to left-align everything

VCF normalisation is not as important for SVs than SNV as, even with a normalisation strategy, SVs can be represented as either:
1) direct read bases (e.g ref=AAAA, alt=A)
2) symbolic allele (e.g <DEL>)
3) BND notation

To actually compare calls from different SV caller you need to convert them all into a standardised format. I wrote the StructuralVariantAnnotation BioConductor R package to do exactly this.
