### ISSUE TITLE
NonReferenceContigAssembler Missing Contigs Errors

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#302]
I have the following errors

```
ERROR	2020-02-20 06:40:27	NonReferenceContigAssembler	Sanity check failure: non-empty graph with no contigs called chr1
ERROR	2020-02-20 07:27:34	NonReferenceContigAssembler	Sanity check failure: non-empty graph with no contigs called chr5
ERROR	2020-02-20 07:47:51	NonReferenceContigAssembler	Sanity check failure: non-empty graph with no contigs called chr7
ERROR	2020-02-20 08:00:58	NonReferenceContigAssembler	Sanity check failure: non-empty graph with no contigs called chr8
ERROR	2020-02-20 08:05:06	NonReferenceContigAssembler	Sanity check failure: non-empty graph with no contigs called chr8
```

There are no other errors in the log apart from the ones shown. I am confused why they happen for a few chromosomes and not for most others.

**Comment by d-cameron** [comment]
They're an assembly edge case that I haven't been able to track down because I haven't yet found a managable size bam that will reproduce the issue. It's hard to debug since GRIDSS (uniquely) does streaming assembly so the low-level state of the assembly graph depends on previous reads that were loaded, processed, and unloaded (hence why subsetting the bam doesn't reproduce the error).

When GRIDSS detects a sanity failure, it flushes the graph and reloads the reads that were in the graph, resetting to a clean low-level state (e.g. hash tables sizes, kmer lookups, etc), but (in theory) not affecting the graph itself.

**Comment by d-cameron** [comment]
TDLR: not an issue for the end result, really hard to debug, and I'll be replacing the assembler with a faster one in the next 12 months.
