### ISSUE TITLE
PositionalAssembler Error - uploaded .zip file

### ISSUE THREAD

**Issue by RobinVanSchendel** [PapenfussLab/gridss#319]
I got this error:

WARNING 2020-04-07 04:31:20     PositionalAssembler     Error during assembly of chromosome 4 (221643 reads in graph). Attempting recovery by rebuilding assembly graph

I have uploaded the accompanying zip file. I hope you can solve this problem.

[gridss_minimal_reproduction_data_for_error_1.zip](https://github.com/PapenfussLab/gridss/files/4444647/gridss_minimal_reproduction_data_for_error_1.zip)

**Comment by d-cameron** [comment]
The attached file appears to be incomplete or corrupt as it only contains the masked reference genome. Are you able to rerun, confirm that the `gridss_minimal_reproduction_data_for_error_1.zip` file also contains files in _input_.gridss.working/ directories, and reupload?

**Comment by d-cameron** [comment]
I've checked over the code and it's possible that the corruption is due to an early termination due assembly errors on multiple threads (only the first is exported, but the second can cause GRIDSS to exit before the first error has completed packaing up the minimal data for reproduction). When you rerun, please do so with with WORKER_THREADS=1.

Alternatively, if an `*.error_package` directory exists (`find . -name '*.error_package') because GRIDSS exited before it could get cleaned up, can you zip up the contents of that directory and upload it?

**Comment by RobinVanSchendel** [comment]
There was no such directory '*.error_package'. I am currently rerunning on a single thread and I will let you know. If that does not work out I will test your latest commit and see if that now outputs a useful debug file.

**Comment by RobinVanSchendel** [comment]
I ran the command again on a single thread. GRIDSS now finishes without any problem. For now I will close this bug because I cannot reproduce the problem.
