### ISSUE TITLE
IHOMPOS is not symmetrical for all breakend

### ISSUE THREAD

**Issue by alkodsi** [PapenfussLab/gridss#33]
I hope the gridss manuscript is coming soon so some things are better understood.  I have some questions about output of gridss:
- What is inexact homology position and how is it related to homology length? The IHOMPOS has two values for each break end, how do they differ (they are not mirrored between the two break ends)?
- SVLEN is NA for all my SVs, how can I calculate it?
- Is there a way to calculate variant allele frequencies?

**Comment by d-cameron** [comment]
Inexact homology position is the bounds of a smith-waterman alignment (using a bwa scoring matrix) relative to the nominal breakend position. The value is an interval over which the breakpoint would be essentially the same variant call. A value of [-50, 100] would mean that the breakend position could be moved 50bp towards to start of the chr, or 100bp towards the end of the chr and the variant call would be mostly the same. It has the same meaning as HOMPOS but does not require the homology to be exact.
The different breakends of the same call having different values does seem like a bug - I'll look into it and add more test cases for all possible pairs of breakend orientation.

SVLEN is not meaningful for inter-chromosomal events. If you've already filtered these out and only retain intra-chromosomal events, you can calculate in R it using `svlen <- abs(start(rowRanges(vcf)) - start(rowRanges(vcf)[info(vcf)$PARID]))`

What do you consider the variant allele frequency of a structural variant to be? A SV could be homozygous at one breakend and heterozygous at the other. Breakend VAF can be calculated as follows:
`
library(StructuralVariantAnnotation)
df <- unpack(vcf)
df$Reads <- df$ASCSR + df$SR + df$RSR
df$Pairs <- df$ASCRP + df$RP
df$VariantAlleleFreq.Reads <- df$Reads / (df$Reads + df$REF)
df$VariantAlleleFreq.Pairs <- df$Pairs / (df$Reads + df$REFPAIRS)
`
Note that due to the lower mapping rate of split reads, a VAF of less than 0.5 is to be expected for simple heterozygous events.

**Comment by alkodsi** [comment]
Thanks a lot. So is there a biological meaning behind the inexact homology? I first thought that HOMLEN refers to microhomology at the break junction and IHOMPOS refers to microhomolgy at a close-by region, such as Figure 1 in this review: 
http://www.sciencedirect.com/science/article/pii/S016895251400002X

But apparently it is something else.

**Comment by d-cameron** [comment]
It was included for technical, not biological reasons. Variant calls between sequences that are almost identical are likely to be false positive calls. For example, almost every sample I've processed has an apparent translocation between NOTCH2 and and a NOTCH2 pseudogene. This apparent translocation is not an actual biological event, but an artifact of the reference genome sequence at the two locations.
Take the following sequence:
```
CACATAATCTTCTAATCTGACTTGACTGAAGTCGTACCTGACAAAGTTGATTTATCAGTGGCAAATCTTCACCTGTTGAATTCATAAGTTCATGTCTGAAAGGTGAGAATAAATACTTAATATTCACTAGGTAATTTCAGCAAAGTA
------------------------------------------------------------\
                                                             |                                                                                      
															 ------------------------------------------------------------------------------------
CACATAATCTTCTAATCTGACTTGACTGAAGACGTACCTGACAAAGTTGATTTATCAAGTTGTAAATCTTCACCTGTTGAATTCATAAGTTCATGTCTGAAAGGTGAGAATAAATACTTAATATTCACTAGGCAATTTCAGCAAAGTA
```
There is a 2bp homology (TG ) across the breakpoint so the homology length is 2. If it wasn't for an inexact homology check, you wouldn't know that the entire event signal is driven by a 3 base pair difference between two also identical sequences.

**Comment by alkodsi** [comment]
Should I add a filtering criteria based on IHOMPOS then to avoid this kind of false positives?

**Comment by d-cameron** [comment]
Probably, although it depends on your data set and question you are studying. Personally, I manually check a few with high IHOMPOS in IGV to see what sort of variants I'm getting then filter based on that.

**Comment by alkodsi** [comment]
I am looking at your code for calculating allele frequencies. Shouldn't it be like this:

df$Reads <- df$ASCSR + df$SR 
df$Pairs <- df$ASCRP + df$RSR
#I don't know if df$RP has an equivalent on the other end

df$VariantAlleleFreq.Reads <- df$Reads / (df$Reads + df$REF)
df$VariantAlleleFreq.Pairs <- df$Pairs / (df$Pairs + df$REFPAIR)

**Comment by d-cameron** [comment]
The initial formula is correct. The relevant fields are as follows:
```
##INFO=<ID=ASCRP,Number=.,Type=Integer,Description="Count of read pairs not directly supporting breakpoint incorporated into any breakpoint assembly">
##INFO=<ID=ASCSR,Number=.,Type=Integer,Description="Count of split or soft clipped reads not directly supporting breakpoint incorporated into any breakpoint assemblies">
##INFO=<ID=ASRP,Number=.,Type=Integer,Description="Count of read pairs incorporated into any breakpoint assembly">
##INFO=<ID=ASSR,Number=.,Type=Integer,Description="Count of split or soft clipped reads incorporated into any breakpoint assemblies">
##INFO=<ID=REF,Number=.,Type=Integer,Description="Count of reads mapping across this breakend per category">
##INFO=<ID=REFPAIR,Number=.,Type=Integer,Description="Count of reference read pairs spanning this breakpoint supporting the reference allele per category">
##INFO=<ID=RP,Number=.,Type=Integer,Description="Count of read pairs supporting breakpoint per category">
##INFO=<ID=RSR,Number=.,Type=Integer,Description="Count of split reads supporting breakpoint from remote breakend per category">
##INFO=<ID=SR,Number=.,Type=Integer,Description="Count of split reads supporting breakpoint per category">
```

Whether a split read is considered local or remote to the reported break-end depends on whether the initial soft clipped alignment was local or remote (hence why the values of `SR` and `RSR` are swapped when looking at the other break-end). By contrast read pair counts are necessarily the same at both break-ends as the read pairs have one read aligned to each side. On my TODO list is support for the split read alignment that BWA natively outputs, at which point the distinction between local and remote would no longer make sense as both positions are reported by the aligner.

The total direct support for split reads spanning a breakpoint is the sum of the split reads from local soft clips `SR`, and the split reads from remote soft clips `RSR`. The total direct for read pairs supporting a breakpoint is `RP`.

Assembly descriptions are actually slightly misleading as the counts of split reads `ASSR` and read pairs `ASRP` include soft clipped reads not able to be unambiguously identified as split reads (too few bases, or multiple possible mapping locations), and "OEA" reads in which only one end is mapped. The conscripted counts `ASCSR` `ASCRP` are the split reads and read pairs which do not directly support the variant call (because one side maps to a different location), but were successfully assembled, and support the breakpoint as part of the assembly. If we just added `ASSR` and `ASRP` we would the double-counting the reads that provide direct support, and were successfully assembled into a supporting assembly.

I hope that makes sense.

**Comment by d-cameron** [comment]
FYI: variant allele fraction can now be accurately calculated using the new `VF` field.
