### ISSUE TITLE
Same Read Offset Warning

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#341]
Is there an option to bwa which would avoid the warnings? An example is:

```
WARNING	2020-05-12 18:06:23	SAMRecordUtil	Found two read alignments starting at the same read offset for read A00121:72:HG2WFDSXX:1:1101:1316:17143 (chr13:18211999 and chrUn_JTFH01001465v1_decoy:550). Ignoring one. Note that GRIDSS does not support multiple (non-split) alignments for a single read such as those output by 'bwa mem -a'.
```

The `-a` option of `bwa mem` was not used.

```
@PG     ID:bwa  PN:bwa  CL:bwa mem -p -t 8 -R @RG\tID:HG2WVDSXX.1_OSCC_1-P_1\tPL:illumina\tPU:HG2WVDSXX.1\tSM:OSCC_1-P\tLB:OSCC_1-P_1\tCN:AGRF -M Reference/hs38DH.fasta -   VN:0.7.17-r1188
```

**Comment by d-cameron** [comment]
Are the reads in question actually have split read alignments that end at the same position?
On my bwa data, it appears that this happens with some reads that are aligned to hg38 alt contigs. The issue appears to be that bwa allows split alignments to alt contigs that can extend so far they completely overlap the primary alignment itself. I've also seen bwa split read alignments in which one of the alignments is completely contained within other alignments. This doesn't make sense as you could just remove that alignment and no fewer bases would be aligned. I'm not sure why bwa reports these. I see two resolutions to this issue:

1) raise an issue with bwa and hopefully someone will fix bwa so that either a) it doesn't report invalid split read alignment or b) the circumstances in which this happens are properly documented. 

2) Add additional logic to GRIDSS preprocessing to explicitly handle split read alignments that are not actually valid split read alignments. I'd still want GRIDSS to report a warning in this case as the alignments don't actually make sense.

I've already put it a fix in v2.9.1 to only log this message 100 times as the full log file ends up ridiculously large otherwise.

**Comment by DarioS** [comment]
> Are the reads in question actually have split read alignments that end at the same position?

I think it does, but I am not sure because I am not confident interpreting the alignment. My interpretation is the read is 150 bases and the primary alignment uses all 150 bases, but the supplementary also uses all 150 bases, but they should be disjoint rather than totally overlapping. It is

```
A00121:72:HG2WFDSXX:1:1101:1316:17143   65      chr13   18211999        0       150M    chr21   10325744        0       TTTGTGTTTTTATTTTCCCTGTGTTTGCTTTTTCTCATGGGGAACCTGTGTTGCTGCTTTGAAGGTATATTCATACTGGCCTTTCAAATGCCAACTCTTCAAATTACTAGTTAAGGCTTTCAAAATATGTTATTTAAAAAATTATCCTCT  @BCBBAACCCCAACCCA=0CAAAACCA?CCCCCACA9AA@@@BB?<CAAAACABCA.CCCA:;B@AAAAACAAAA:CA@BACCCAABBAACBAC?DBDDAB:CBDB@D8CBDBCCACD=DBBC9CBBBBBDBBDDBC:C:CBDBB=CEBC  SA:Z:chrUn_JTFH01001465v1_decoy,550,+,150M,6,8; MC:Z:150M       MD:Z:6G3C10A0T4A7T21A2C7G13G8G22T35     RG:Z:HG2WFDSXX.1_OSCC_1-N_1     NM:i:12 AS:i:90 XS:i:70 pa:f:0.818      om:i:31
A00121:72:HG2WFDSXX:1:1101:1316:17143   129     chr21   10325744        0       150M    chr13   18211999        0       TTCACTGTATTGGCCAGGACGGTCTTGATCTCTTCACCTTGTGATCCCCTTGCCTTGGCCTCCAAATTTGCTGGGATTACAGGCCTGAGCCAAGATCCATATTTTTTAAATGAAAAAAAATTTCAAAGGTACTCTTCTTGGTACAATAAT  >B>A-BAAAACA@BAAB@B?:@AACCABAACACC:6?ACCAAABAAAAACC9BAC;A@BACAAABB@CCABCA@@BACA?AA@B8CA7BBAABBBAAAAAA*CCCCCA7*AA7B7*B7779C;AAB*C@AB@>BDDBDDAABB@(DCBCA  SA:Z:chrUn_JTFH01001680v1_decoy,312,-,150M,18,6;        MC:Z:150M       MD:Z:19T12C14T5T9G2A47G20G7A6   RG:Z:HG2WFDSXX.1_OSCC_1-N_1     NM:i:9  AS:i:105        XS:i:105        pa:f:0.875      om:i:0
A00121:72:HG2WFDSXX:1:1101:1316:17143   2113    chrUn_JTFH01001465v1_decoy      550     6       150M    chr21   10325744        0       TTTGTGTTTTTATTTTCCCTGTGTTTGCTTTTTCTCATGGGGAACCTGTGTTGCTGCTTTGAAGGTATATTCATACTGGCCTTTCAAATGCCAACTCTTCAAATTACTAGTTAAGGCTTTCAAAATATGTTATTTAAAAAATTATCCTCT  @BCBBAACCCCAACCCA=0CAAAACCA?CCCCCACA9AA@@@BB?<CAAAACABCA.CCCA:;B@AAAAACAAAA:CA@BACCCAABBAACBAC?DBDDAB:CBDB@D8CBDBCCACD=DBBC9CBBBBBDBBDDBC:C:CBDBB=CEBC  SA:Z:chr13,18211999,+,150M,31,12;       XA:Z:chr13,+18211999,150M,12;chrUn_JTFH01001680v1_decoy,+96,150M,9;chrUn_JTFH01001478v1_decoy,+1,41S109M,2;chrUn_JTFH01001430v1_decoy,+108,150M,12;     MC:Z:150M       MD:Z:6G14A3G1A36T25T19A3T35     RG:Z:HG2WFDSXX.1_OSCC_1-N_1     NM:i:8  AS:i:110        XS:i:105
A00121:72:HG2WFDSXX:1:1101:1316:17143   2193    chrUn_JTFH01001680v1_decoy      312     18      150M    chr13   18211999        0       ATTATTGTACCAAGAAGAGTACCTTTGAAATTTTTTTTCATTTAAAAAATATGGATCTTGGCTCAGGCCTGTAATCCCAGCAAATTTGGAGGCCAAGGCAAGGGGATCACAAGGTGAAGAGATCAAGACCGTCCTGGCCAATACAGTGAA  ACBCD(@BBAADDBDDB>@BA@C*BAA;C9777B*7B7AA*7ACCCCC*AAAAAABBBAABB7AC8B@AA?ACAB@@ACBACC@BBAAACAB@A;CAB9CCAAAAABAAACCA?6:CCACAABACCAA@:?B@BAAB@ACAAAAB-A>B>  SA:Z:chr21,10325744,+,150M,0,9; XA:Z:chr21,+10325744,150M,9;chr21,-10270285,150M,9;chrUn_JTFH01001465v1_decoy,-766,150M,8;chrUn_JTFH01001512v1_decoy,+1142,112M1I37M,8;chrUn_JTFH01001724v1_decoy,+607,150M,10;chrUn_JTFH01001478v1_decoy,-176,79M1I70M,10;     MC:Z:150M       MD:Z:14C16G16G4T66A9A19 RG:Z:HG2WFDSXX.1_OSCC_1-N_1     NM:i:6  AS:i:120        XS:i:110
```

It seems like a bug in bwa and I'll make a report there if you can confirm my interpretation of it. But bwa seems like abandonware which hasn't had a real update in a couple of years. We can only hope ...

**Comment by d-cameron** [comment]
It is indeed a bug in bwa. It seems to occur between an alt contig and a primary alignment in which the edit distance is high. My guess itsthat the SNVs caused big gap in seeds so bwa looked for alt alignments, but then the s/w extensions to produce the final alignments resulted in full extension of all records. That approach would also explain when I sometimes see split read alignment records that are covered by multiple other records (e.g. 50S50M, 50M50S, and 25S50M25S - that third record is unnecessary).
