### ISSUE TITLE
Updating docker GRIDSS version 2.9.4 =>2.10.x

### ISSUE THREAD

**Issue by TnakaNY** [PapenfussLab/gridss#423]
Could you update docker img version of gridss in dockerhub? 

Current docker gridss version is v2.9.4.
It is easy to use newest version in HPC with Singularity, not docker so that we can use it quickly without local image building in PC with docker.

**Comment by drashwinelkar** [comment]
Getting this error with three different version of GRIDSS from singularity or docker :

"$timecmd java -Xmx4g $jvm_args -cp $gridss_jar gridss.analysis.CollectGridssMetrics I=$assembly O=$prefix REFERENCE_SEQUENCE=$reference THRESHOLD_COVERAGE=$maxcoverage TMP_DIR=$workingdir FILE_EXTENSION=null GRIDSS_PROGRAM=null GRIDSS_PROGRAM=CollectCigarMetrics GRIDSS_PROGRAM=CollectMapqMetrics GRIDSS_PROGRAM=CollectTagMetrics GRIDSS_PROGRAM=CollectIdsvMetrics GRIDSS_PROGRAM=ReportThresholdCoverage PROGRAM=null PROGRAM=QualityScoreDistribution $picardoptions" command completed with exit code 1.

The error always seems to stem from the $timecmd
Any ideas how to go around this ?

**Comment by d-cameron** [comment]
Working on it. The new tools have additional requirements and I w
Also wanted to build an image that includes the virusbreakend database so
the image building for 2.10 is a bit more involved than just rerunning the
dockerfile (although that would work if you only needed it for SV calling)

**Comment by d-cameron** [comment]
>Getting this error with three different version of GRIDSS from singularity
or docker :

What's the error message in the full log file? The path to the full log
file is printed as one of the first messages.

timecmd is just /usr/bin/time if it exists or nothing if it doesn't.
Everything gridss runs is wrapping in it so timing info for each step is
available. That particular step is the metrics calculation of the assembly
output. Maybe it doesn't like your assembly file not having a .bam (or .Sam
or .cram) suffix (would need to see the log file to be sure)

**Comment by drashwinelkar** [comment]
Tue Nov  3 08:30:38 UTC 2020: Full log file is: ./gridss.full.20201103_083038.1f43d95f7d0c.264.log
Tue Nov  3 08:30:38 UTC 2020: Found /usr/bin/time
_**Tue Nov  3 08:30:38 UTC 2020: Unexpected /usr/bin/time version. Not logging timing information.**_

08:30:39.680 INFO  NativeLibraryLoader -
08:30:40.505 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/gridss-2.9.4-0/gridss.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Nov 03 08:30:40 GMT 2020] CollectGridssMetrics GRIDSS_PROGRAM=[CollectCigarMetrics, CollectMapqMetrics, CollectTagMetrics, CollectIdsvMetrics, ReportThresholdCoverage] THRESHOLD_COVERAGE=50000 INPUT=DNA_2_chad_bowtie_sorted.bam 
08:30:40.505 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/gridss-2.9.4-0/gridss.jar!/com/intel/gkl/native/libgkl_compression.so

[Tue Nov 03 08:30:40 GMT 2020] CollectGridssMetrics GRIDSS_PROGRAM=[CollectCigarMetrics, CollectMapqMetrics, CollectTagMetrics, CollectIdsvMetrics, ReportThresholdCoverage] THRESHOLD_COVERAGE=50000 INPUT=DNA_2_chad_bowtie_sorted.bam 

OUTPUT=./DNA_2_chad_bowtie_sorted.bam.gridss.working//DNA_2_chad_bowtie_sorted.bam FILE_EXTENSION=null PROGRAM=[QualityScoreDistribution] TMP_DIR=[.] REFERENCE_SEQUENCE=ChAdOx1nCov19_scaffolds_RC.fa    ASSUME_SORTED=true STOP_AFTER=0 METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false

[Tue Nov 03 08:30:40 GMT 2020] Executing as root@1f43d95f7d0c on Linux 5.4.0-1028-gcp amd64; OpenJDK 64-Bit Server VM 11.0.1-internal+0-adhoc..src; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.9.4-gridss
[Tue Nov 03 08:30:40 GMT 2020] gridss.analysis.CollectGridssMetrics done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=790626304

**_Exception in thread "main" htsjdk.samtools.SAMException: Cannot write file: /data/./DNA_2_chad_bowtie_sorted.bam.gridss.working/DNA_2_chad_bowtie_sorted.bam.cigar_metrics. Neither file nor parent directory exist_**
______________________________________________________________________________________________________
The above is the only error I could find in the log file, but that error should not be there since this is a container, no issues with permissions etc.
and the command line error is this following -

"$timecmd java -Xmx4g $jvm_args -cp $gridss_jar gridss.analysis.CollectGridssMetrics I=$assembly O=$prefix REFERENCE_SEQUENCE=$reference THRESHOLD_COVERAGE=$maxcoverage TMP_DIR=$workingdir FILE_EXTENSION=null GRIDSS_PROGRAM=null GRIDSS_PROGRAM=CollectCigarMetrics GRIDSS_PROGRAM=CollectMapqMetrics GRIDSS_PROGRAM=CollectTagMetrics GRIDSS_PROGRAM=CollectIdsvMetrics GRIDSS_PROGRAM=ReportThresholdCoverage PROGRAM=null PROGRAM=QualityScoreDistribution $picardoptions" command completed with exit code 1.

I don't know why this exception is arising, since I am running it in a docker container, permissions should not be a problem.

**Comment by d-cameron** [comment]
>Tue Nov 3 08:30:38 UTC 2020: Full log file is: ./gridss.full.20201103_083038.1f43d95f7d0c.264.log

What's the error message in that file?

**Comment by TnakaNY** [comment]
Working on it. The new tools have additional requirements and I w
Also wanted to build an image that includes the virusbreakend database so
the image building for 2.10 is a bit more involved than just rerunning the
dockerfile (although that would work if you only needed it for SV calling)

==> Thank you!

**Comment by illusional** [comment]
Commenting to add support for latest GRIDSS in Docker (and also so it subscribes me to the issue).

**Comment by d-cameron** [comment]
2.10.2 release with docker image
