### ISSUE TITLE
Reference genome hs37d5 usage

### ISSUE THREAD

**Issue by TnakaNY** [PapenfussLab/gridss#424]
Please let me confirm my understandings for reference genome. I am beginner for NGS analysis.

My bam files were mapped to hs37d5. I already made index files of hs37d5 and located in reference directory.

As long as using hg19 (hs37d5, b37, gatk.illumina (downloaded from GIRDSS-PURPLE-LINX developers site) etc), no need to remake any other reference files like hg19.fa.out.bed for Repeatmasker ref.

Just changing reference genome files (refdata/refgenomes/Homosapience/Homosapience.fasta, fasta.fai, etc) to hs37d5 version is fine?

**Comment by d-cameron** [comment]
GRIDSS itself is reference genome agnostic and does not require any specific reference genome.

>Just changing reference genome files (refdata/refgenomes/Homosapience/Homosapience.fasta, fasta.fai, etc) to hs37d5 version is fine?

The GRIDSS/PURPLE/LINX pipeline only officially supports the hg19 and hg38 reference included in the Hartwig reference data downloads. We have not tested against other references and many/all of the follow files may or may not be required to be changed for it to work with hs37d5:
```
dbs/ensembl_data_cache/ensembl_gene_data.csv
dbs/gc/GC_profile.1000bp.cnp
dbs/germline_het_pon_hg19/GermlineHetPon.hg19.bed
dbs/germline_het_pon_hg19/GermlineHetPon.hg19.vcf.gz
dbs/sv/fragile_sites_hmf.csv
dbs/sv/line_elements.csv

```

Even if all these files were changed, it still might not work.

Some features such as the ability to detect viral integrations are known to be broken on hs37d5 since that reference include a decoy sequence containing the EBV genome.

You'll need to realign your reads if you want to run GRIDSS/PURPLE/LINX.

**Comment by TnakaNY** [comment]
Hi,
Thank you for your comments. 
For only GRIDSS usage, to select somatic SV from raw GRIDSS output vcf files, I still need to use somaticfiltering.R

For this R script, GC_profile.1000bp.cnp etc files. These files include chromo start, end position information.
Do these position change if we use different version of hg19 reference (g1k, b37, etc)?

If not, i guess, somaticfileteringRscript should work with hs37d5 reference too.

**Comment by d-cameron** [comment]
`gridss_somatic_filter.R` uses only the GRIDSS PON files which should be valid for any dialect of hg19 (or hg38 if using the hg38 PON).
