### ISSUE TITLE
Q: Is there a way to adjust quality parameter to improve sensitivity

### ISSUE THREAD

**Issue by hansolo-bioinfo** [PapenfussLab/gridss#456]
Hi, 

Currently, our group is using unfiltered VCF by GRIDSS as our upstream analysis. We have tried both SvABA and GRIDSS. 
Looks like GRIDSS missed the SV in the below 'sample' because of LOW_QUAL. I would like to know if there is a way to control the LOW_QUAL or if there would be a parameter to increase number of supportive assembly reads for this.

btw, could you please explain what 'AS=1;ASC=57M1X1N1X;ASQ=161.24;A' means? especially 'AS' and 'ASQ'.
Thank you! 

Best,
Han

[sample.txt](https://github.com/PapenfussLab/gridss/files/5985538/sample.txt)

**Comment by d-cameron** [comment]
They're all defined in the VCF header. GRIDSS gives a full breakdown (both total and per-sample) of the suppport for each variant.

The default GRIDSS filters aren't the best: LOW_QUAL is literally just a QUAL>=500 check (with a higher threshold for single breakends), and the others are all also simple filters that can be inferred from the other fields (e.g. `SINGLE_ASSEMBLY`=`AS+RAS=1). See https://github.com/PapenfussLab/gridss/blob/master/src/main/java/au/edu/wehi/idsv/configuration/VariantCallingConfiguration.java#L165 for details.

If you're looking at cancer samples, we've put a lot of effort into good filtering of the raw GRIDSS VCF and we now have support for tumour-only sequence. These filters ignore the VCF `FILTER` and redo the filtering from the `INFO` and `GENO` fields. If you're looking at germline samples, we unfortunately don't yet have an equivalent high quality filter (although we do have a PhD student working on the more general version of this problem).

Have a read of the descriptions in the VCF header and let me know if there's anything unclear. Remember that GRIDSS does independent *breakend* assembly for each loci so a breakpoint should have two supporting assemblies (one from each side). This is different to the breakpoint assembly approach of manta/svaba.

Some clarifications on those fields:

- `AS` is the count of supporting assemblies *that were assembled from this side of the breakpoint*. For assemblies from the other side, you want to look at `RAS`
- `ASC`: The XNX notation is used to encode the possible positions of the breakpoint relative to the variant location so `57M1X1N1X` indicates that the 57 bases before the breakpoint (which has a 3bp microhomology) are supported by assembly. 57bp is pretty short and is indicative of a low quality call, or a high quality call with a cis-phased SV 57bp before it
- `**Q` are the breakdown of the QUAL score by support. GRIDSS's scoring model treats everything as independent so total QUAL is just `sum(**Q)` since the field is phred scaled. In practice, this massively overestimates the qual since assembly is not independent of it's constituent reads nor are alignments mapqs independent (since aligners are systematic in their errors) nor are a split read + discordant read pair from the same originating fragment.


> I would like to know if there is a way to control the LOW_QUAL 

In a technical sense, this is defined in following lines in the default configuration file:
```
variantcalling.breakpointLowQuality = 500.0
variantcalling.breakendLowQuality = 1500.0
```
which you can override by supplying a file containing different values in the  `--configuration` command line argument.

In a practical sense, you'd be better off QCing the calls and making creating an actually good set of germline filters. I got some really good results training a random forest classifier based on gridss output + repeatmasker annotation but it didn't generalise enough across the huge diversity (both technical and biological) of data GRIDSS is used on so it didn't make it into the codebase.

**Comment by hansolo-bioinfo** [comment]
Thanks for the quick reply! I am clear what is going on.

**Comment by d-cameron** [comment]
Ok, from your sample.txt I see you're doing tumour/normal sequencing. I strongly recommend using GRIDSS/PURPLE/LINX pipeline we've spent the last few years developing. We're doing scale (8000+ patients) clinical reporting based on it and have some key differentiators including:

- holistic driver gene prediction based on SNVs/indel/CN/SVs (need to feed PURPLE the tumour SNV/indel VCF)
  - complex driver fusion prediction (only previously done using RNA-seq)
  - homozygous gene disruption prediction
- genomic rearrangement classification
  - accounts for genomic shards
- the best complex event visualisation (kudos to my colleagues that did the work for this)
- base-pair accurate SV+CN calls
- germline aneuploidy handling
- a SV FNR lower than that achievable with a breakpoint-based caller (see GRIDSS2 preprint)

Disclaimer: designed for fresh samples 100x/40x tumour/normal sequencing. Likely to be overly conservative on (e.g.) low coverage FFPE samples.

References:
https://www.hartwigmedicalfoundation.nl/en/
https://www.biorxiv.org/content/10.1101/781013v1 (summary preprint)
https://www.biorxiv.org/content/10.1101/2020.07.09.196527v1 (more detailed GRIDSS2 preprint) (v2 waiting on biorvix verification - should only be a day or two)
https://www.biorxiv.org/content/10.1101/2020.12.03.410860v1 (more details LINX preprint)
https://github.com/hartwigmedical/hmftools/blob/master/sv-linx/README_VIS.md

**Comment by d-cameron** [comment]
This is probably my favourite demonstration: it's a complex rearrangement that results in 3 drivers:

- A functional TMPRSS2-ERG fusion that goies via PTEN intron1 (follow the light blue line)
- homozygous distruption of PTEN (exon1 is on a different derivate chromosome to the rest)
- loss of 1 copy of PPP2R2A

Being able to report these drivers is extremely non-trivial amount of work. AFAIK, we're the only toolkit that can do it and LINX requires both PURPLE and GRIDSS (and PURPLE requires GRIDSS) so it does unfortunately force you into using GRIDSS/PURPLE/LINX together (at least until someone else develops a tool with equivalent functionality).

![image](https://user-images.githubusercontent.com/6036536/108018173-06090c80-706b-11eb-8eb1-ecca41b2da53.png)

**Comment by d-cameron** [comment]
And in case you were wondering, yes that figure came straight out of LINX.

**Comment by hansolo-bioinfo** [comment]
Thank you for this detailed answers! I will definitely try this pipeline. Currently we are using GRIPSS for the filtering steps.
