### ISSUE TITLE
Input sanity check failure - different read lengths

### ISSUE THREAD

**Issue by hrkemp** [PapenfussLab/gridss#465]
I'm receiving a warning in my output logs, such as ..

"Input sanity check failure: different alignment records imply different read lengths HISEQ101_164:4:2102:2199:71084. This can be cause by GATK indel realignment incorrectly removing hard clipped bases when realigning. Do not use GATK indel realigned BAM files with GRIDSS."

Is this a warning that can be ignored, or does it require action?

I am supplying trimmed, recalibrated bams.

The reads for this alignment ID are:

HISEQ101_164:4:2102:2199:71084	339	chr15	17083300	25	78H32M40H	=	17083294	-38GAGTGGAGTGGAGTGTAGGTGAGTGGAGTGGA	:<9;;:29:91;9::<<;:;;;:;;;<KLK>A	SA:Z:chr15,17083289,-,47S43M60S,54,0;chr15,17083300,-,98S52M,27,2;chrY,10971444,+,109S37M4S,16,1;	XA:Z:chr21,+10722993,40S32M78S,1;chrY,+10974168,37S36M77S,2MD:Z:32	PG:Z:MarkDuplicates	RG:Z:232024	NM:i:0	AS:i:32	XS:i:27

HISEQ101_164:4:2102:2199:71084	339	chr15	17083300	27	98H52M	=	17083294	-58	GAGTGGAGTGGAGTGTAGGTGAGTGGAGTGGATTGGAGTGCACTGGACTGGA	<<;<<<=:;;9<:;::15:;;<:;;;29;9:;<;;;;95:,:<;;;;>>==<	SA:Z:chr15,17083289,-,47S43M60S,54,0;chr15,17083300,-,78S32M40S,25,0;chrY,10971444,+,109S37M4S,16,1;	MD:Z:33C4A1PG:Z:MarkDuplicates	RG:Z:232024	NM:i:2	AS:i:42	XS:i:33

**Comment by d-cameron** [comment]
GRIDSS assumes that hard clipped reads are due to bwa-style split read alignments in which the primary alignment is soft clipped and the supplementary alignments are hard clipped. GRIDSS converts these hard clips back to soft clips so it can perform assembly of the supplementary alignments.

>I am supplying trimmed

What did your trimming software do? Did your trim the fastq, or some sort of alignment-based trimming? If it's the latter, does your tool correctly handle split read alignments?

If all partial alignment were hard clipped then you've just removed your entire split read signal and you'll need to realign without deleting half your SV support.

> recalibrated bams.

BQSR is fine. IndelRealigner is problematic since it doesn't update the SA tags correctly when it adjusts alignment positions.

> Is this a warning that can be ignored, or does it require action?

It is a warning. GRIDSS is unable to rehydrate the hard clips for that read (because there's no full-length sequence available).
