### ISSUE TITLE
Does GRIDSS work well with low-pass genome data?

### ISSUE THREAD

**Issue by kvn95ss** [PapenfussLab/gridss#490]
I have a low-pass genome data and was wondering if GRIDSS would be a good option to call duplications in the sample.

**Comment by d-cameron** [comment]
GRIDSS outperforms other SV calling tools due to it's incorporation of assembly. Low depth genome data reduces the reliability of assembly thus the difference between gridss and tools like delly or lumpy is less on such data.

That said, if you're doing low-pass sequencing on many samples, you can do GRIDSS joint calling. This increases the effective coverage of common variants thus fixing the low-coverage assembly reliability issue for these.
