### ISSUE TITLE
Normal and tumour supporting reads in GRIDSS output vcf

### ISSUE THREAD

**Issue by orsolyasipos** [PapenfussLab/gridss#492]
Hi, 

I have run GRIDSS on triple negative breast cancer WGS samples (matched tumour and normal) and in the output vcf file I wanted to compare the reads that are supporting the reference and variant alleles. According to the vcf header, I should compare RF and VF, however, RF is not reported in my vcf files. I was wondering what could be the most appropriate measure for this, e.g. comparing REFPAIR and RP?

Many thanks for the advice,
Orsolya

**Comment by d-cameron** [comment]
As you noticed, `RF` isn't actually written. It can be calculated as `RF=REF+REFPAIR`.

In terms of calculating VAF:

- Small indels should exclude REFPAIR (since they could be from either the variant or reference)
- single breakends should use BVF
- `gridss_somatic_filter.R` already writes a TAF (VAF in tumour) field
- `libgridss.R` has `gridss_bp_af()` and `gridss_be_af()` functions to do the VAF calculation.
