### ISSUE TITLE
Bugs found in gridss_somatic_filter.R in docker image

### ISSUE THREAD

**Issue by jiaan-yu** [PapenfussLab/gridss#509]
Hi,

I have found several bugs when I running the gridss_somatic_filter.R in docker image (version 2.11.1 in quay).
1) Olson database is not installed.
2) Script asks for reference genome, and try to download and install package if not found. It is not possible to install packages in the image.
3) Generated plots have characters shown as blocks because of missing fonts.
4) The default values of --scriptdir / --configdir are incorrect. Users have to specify the full path of gridss library in the image

I have a workaround with the following commands, but it would be great if those bugs can be addressed.

```
singularity run \
  --bind /usr/share/zoneinfo:/usr/share/zoneinfo \
  --bind /home/jyu/.local/share/rstudio/library/BSgenome.Hsapiens.UCSC.hg19:/usr/local/lib/R/library/BSgenome.Hsapiens.UCSC.hg19 \
  --bind /usr/share/fonts:/usr/share/fonts \
  $image \
  Rscript /usr/local/share/gridss-2.11.1-0/gridss_somatic_filter.R \
 --pondir $pon \
 --ref $ref \
 --input $in.vcf \
 --output $out.vcf \
 --plotdir $dir -s /usr/local/share/gridss-2.11.1-0
```

Thanks!
Jiaan

**Comment by d-cameron** [comment]
> Generated plots have characters shown as blocks because of missing fonts

Unable to reproduce on the latest docker. Maybe it's been fixed since 2.11.1?

> Script asks for reference genome

This parameter is optional. Just don't specify one if you don't have one. Include entire genomes in the image make the image huge since they are ~3Gb per genome and I'd need at least hg19, hg38, and mm10

> try to download and install package if not found.

Unable to reproduce. Specifying `--ref BSgenome.Hsapiens.UCSC.hg19` gives follow error:

`Error: Missing reference genome package BSgenome.Hsapiens.UCSC.hg19`

This error message is the intended behaviour.
