### ISSUE TITLE
Disk access pattern: is there a way to avoid resorting of the BAM?

### ISSUE THREAD

**Issue by cassisnaro** [PapenfussLab/gridss#510]
Hi,
we are trying to minimise how much the different tools in our pipeline write to disk. We are using gridss through the "gridss" command line. We are under the impression that a significant portion of the write actions of gridss are due to the resorting of the input according to query names. Is this true? Would there be a strategy for us in order to avoid this?
Regards,

**Comment by d-cameron** [comment]
> We are under the impression that a significant portion of the write actions of gridss are due to the resorting of the input according to query names. Is this true?

This is indeed true. GRIDSS has been optimised to minimise (random) disk access. The preprocess step populates the `R2` tag which is then used by the GRIDSS assembler. By queryname, populating R2, then coordinate sorting, GRIDSS avoids the large amount of random I/O that would be required to find the sequence of the mate reads in discordant read pairs.

Note that GRIDSS only does this on the subset of the read that potentially support an SV. This is usually between 5 and 25% of the input file.

> Would there be a strategy for us in order to avoid this?

Yes. This sort can be completely avoided by moving the preprocessing to earlier in the pipeline. If the R2 tag is populated after alignment but before sorting then a queryname sort is not required at all. Similarly, if you're using bwa for alignment, you can skip the SoftClipsToSplitReads step.

I created a proof of concept for this for an older version of GRIDSS, most of which is still applicable. https://github.com/PapenfussLab/gridss/blob/38a2221d3a0d92c1fef782f0ad1a5c734f175407/example/gridss_fully_integrated_fastq_to_vcf_pipeline.sh

Some comments on that scripts:

L109: this piped approach doesn't scale to many core. Htsjdk SAM parsing is single-threaded so gridss.ComputeSamTags quickly bottlenecks in parsing. Adding a multithreaded `samtools view -u` into the pipe will avoid this problem since the htsjdk BAM parser includes my multithreaded decompression/parsing logic.
L122: Q2 is no longer needed so removing it will reduce file size
L132: can be skipped if using bwa for alignment.
L153: By gathering metrics in-line here, we can extract the SV-supporting reads in the second step
L168: Adding R2/Q2 increases the size of the BAM. Since we're also writing the GRIDSS intermediate BAM in this step, we don't need the R2/Q2 in the normal output file. Note that the unsorted intermediate file is large since it contains all reads as well as R2(/Q2) tags.
L173: And now we have all the file in *.gridss.working created and GRIDSS preprocessing done.
L187-: the rest of this script can be replaced with a call to `gridss`. As long as the names and file paths are correct, it'll skip the preprocessing since it'll recognise that it's already done.

Note that if you already have a BAM file then the queryname sort is needed.
