### ISSUE TITLE
Use GRIDDS on wes data

### ISSUE THREAD

**Issue by enes-ak** [PapenfussLab/gridss#517]
Hi,
Is possible to use that tool for whole exome sequencing data or clinic exome panel data? 
Thanks

**Comment by d-cameron** [comment]
Yes, but the vast majority of SVs occur in non-coding sequence so you will get very few calls.

We have had success in calling gene fusions from cancer panel data (e.g. EML-ALK) but to do that we add additional probes tiling the relevant intron to our capture panel. We didn't pick them up with WES.

We also investigated using GRIDSS to do off-target SV calling with limited success. The signal strength is really weak (since you have such low off-target coverage) but by narrowing down the potential regions using CN profile we were able to identify some gene disruptions (e.g. WES coverage changes dramatically between exons -> look for SV in that intron). By 'limited success' I mean that we did find putative driver SVs, but it involved signficant manual intervention/curation and it never made it into any of the clinical pipelines that I've incorporated GRIDSS into.
