### ISSUE TITLE
--skipsoftcliprealignment

### ISSUE THREAD

**Issue by brentp** [PapenfussLab/gridss#524]
hi, this option is shown in the wiki, but I get an error when using it and it's now shown in the help on the command-line. Is it no longer needed?

**Comment by d-cameron** [comment]
Soft clip realignment doesn't do much for bwa aligned input bams because bwa already reports split read alignments^. For inputs aligned with bowtie2 it absolutely is required since bowtie2 only reports soft-clipped alignments, not split read alignments.

This option was added to allow for reduced GRIDSS runtime on bwa-aligned input files. If you are getting errors with `--skipsoftcliprealignment` please raise an issue as it's working on my regression test suite. 


^ somewhat annoyingly, aligning the soft-clipped portion of the soft-clipped (but not split-read aligned) reads with bwa does find some split reads that bwa didn't initially report as split reads.
