### ISSUE TITLE
Question about cutoff for filtering GeneratePonBedpe output

### ISSUE THREAD

**Issue by toddajohnson** [PapenfussLab/gridss#532]
For filtering the files output by GeneratePonBedpe, I am wondering whether the "recommended filtering these output files to only variants found in 3+ samples." is appropriate for PON that are not the size used by HMF (150 versus 3800 samples).  The HMF recommendations for using genome build 37 vs. 38 PONs for filtering SAGE vcf files differed because of the underlying sample size, and while the gridss_pon_breakpoint.bedpe and gridss_pon_single_breakend.bed files for 37 are much larger than the build 38 files, they also appear to have a minimum value of 3 in column 8, while there is a minimum of 1 in column 8 in the build 38 files.
Would if be recommended to adjust the filtering of the GRIDSS PON depending on the PON size?

**Comment by d-cameron** [comment]
> Would if be recommended to adjust the filtering of the GRIDSS PON depending on the PON size?

Yes. It depends not only on the size of the PON but the relative impact of false negative vs false positives for your particular purpose.

For example, I'm involved in a project where we're finding find somatic SV candidates for ctDNA monitoring without matched normals. For this project we only have a relatively small PON (although we do combine it with the Hartwig PON as well), but we're using a threshold of 1 to minimise the impact of false positives (which we have a lot of since we don't have matched normals). Other projects will have different threshold.
