### ISSUE TITLE
Which hg19?

### ISSUE THREAD

**Issue by drmjc** [PapenfussLab/gridss#54]
Hi,
I'm just getting started with GRIDSS, and am stuck running the example. Can you please provide a download link to your specific version of hg19? It doesn't match mine which I got from UCSC, wrt the overall numebr of contigs and their order:

    diff <(samtools view -H /home/dnanexus/gridss/example/chr12.1527326.DEL1024.bam | grep ```

> @SQ | cut -f2 | sed 's/SN://' | sort) <(cat ~/reference_genomes/human/hg19.fa.fai | cut -f1 | sort)
> > 10a11
> > chr17_ctg5_hap1
> 28a30
> > chr4_ctg9_hap1
> 32a35,41
> > chr6_apd_hap1
> > chr6_cox_hap2
> > chr6_dbb_hap3
> > chr6_mann_hap4
> > chr6_mcf_hap5
> > chr6_qbl_hap6
> > chr6_ssto_hap7
> 

The GRIDSS error was:

> Exception in thread "main" htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: In files /home/dnanexus/gridss/example/chr12.1527326.DEL1024.bam and /home/dnanexus/reference_genomes/human/hg19.fa
>         at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:282)
>         at gridss.cmdline.MultipleSamFileCommandLineProgram.ensureDictionariesMatch(MultipleSamFileCommandLineProgram.java:160)
>         at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:199)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
>         at gridss.CallVariants.main(CallVariants.java:107)
> Caused by: htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequence dictionaries are not the same size (84, 93)
>         at htsjdk.samtools.util.SequenceUtil.assertSequenceListsEqual(SequenceUtil.java:188)
>         at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:271)
>         at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:257)
>         at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:280)
>         ... 4 more
> 

cheers,
Mark

**Comment by d-cameron** [comment]
GRIDSS itself is not tied to any particular reference genome (we've used it on human, mouse, and even plasmodium). The reference used in the example was the default reference used by the Papenfuss lab which includes chr1-22,chrX,chrY,chrM, and chr*_gl000*, but chr*_*_hap* were excluded so as to prevent alignments in the corresponding regions being reported as multi-mapping.

In the case of the GRIDSS example, it doesn't matter since all reads in the example are on chr12 and running Picard tools ReorderSam with ALLOW_INCOMPLETE_DICT_CONCORDANCE=true will work fine.

On actual data, I recommend using whatever reference the rest of your pipeline uses.

Make sure you update your GRIDSS jar to version 1.2

**Comment by drmjc** [comment]
true (and v good idea to get rid of the GL+alt haplotypes). I'll just proceed with some b37d5 BAM files. cheers, M
