### ISSUE TITLE
VIRUSBreakend RNA-seq Data

### ISSUE THREAD

**Issue by brownmp** [PapenfussLab/gridss#563]
Hello! 

I was wondering if it was possible to run VIRUSBreakend using RNA-seq data instead of WGS data. 

Best, 
@brownmp

**Comment by d-cameron** [comment]
What outputs are you expecting? If you're looking for viral abundance of RNA viruses, then VIRUSBreakend won't really give you anything that's better than just running kraken2 (which VIRUSBreakend uses to determine which viruses are present). Unless I'm mistaken, the only viral-host integrations you'll see in RNA-seq data are the ones that generate a gene fusion between the virus and an expressed host gene (do those even happen?). You won't see any of the normal viral integration sites because you only see the expressed sequences in RNA-seq data.


So yes should run, but I'm not sure if the output will be meaningful.

**Comment by kojix2** [comment]
At least in hepatitis B, there's a case of a fusion gene being expressed...
