### ISSUE TITLE
Reads supporting individual integrations

### ISSUE THREAD

**Issue by brownmp** [PapenfussLab/gridss#569]
Hello!
I was wondering where to find how may reads support each individual viral integration. I believe must be in the VCF, but I'm unsure where. I see in the Summary file there is a count for total reads, but I'm interested in the count for individual integration events. 

~@brownmp

**Comment by d-cameron** [comment]
The VCF provides a count of supporting fragments^ for each side (breakend) of each integration event in the `BVF` field. For a 'clean' viral integration that VIRUSBreakend detects both sides of the integration, the total number of reads supporting the integration will be the sum of the `BVF` of the two breakends.


^ GRIDSS uses fragment counts instead of read counts to prevent double-counting of paired-end sequenced fragments that provide both read pair support and split read support.

**Comment by brownmp** [comment]
Thank you so much for the help! 
Also, does the VCF file happen to have the viral inserted sequence orientation?

**Comment by d-cameron** [comment]
You can infer that from the position & orientation of the integration in the viral sequence, and the orientation in host genome which is encoded in the `BEALN` field.
