### ISSUE TITLE
questions about gripss.somatic.filtered.vcf.gz 

### ISSUE THREAD

**Issue by mjko1210** [PapenfussLab/gridss#581]
Hi,

gripss works great!

Is there a reason why "PON" is included in final gripss.somatic.filtered.vcf.gz?
`SAMPLE_T.gripss.somatic.filtered.vcf.gz - filtered for PASS and PON only`

I wonder if I need to interpret this "PON" as it was called as somatic, however, it was also presents in PoN database. (Is this correct?)

How do you suggest to deal with PON calls? I wonder if I need to remove them and consider PASS only. 

Thanks,
MJ

**Comment by jamesdalg** [comment]
I'm not a moderator, but this is probably better addressed at the GRIPSS (HMFTools) forum. It's checked much more frequently. I'd suggest going to https://github.com/hartwigmedical/hmftools/tree/master/gripss

**Comment by d-cameron** [comment]
This is indeed best directed to the Hartwig repository.

>I wonder if I need to interpret this "PON" as it was called as somatic, however, it was also presents in PoN database. (Is this correct?)

These events should be interpreted as germline/noise events as they are found in the panel of normals. They are in the somatic VCF because they were not found in the matched normal (usually because the normal was sequenced to a lower depth that the tumour and/or random noise that just happened to occur in the tumour and not that particular matched normal).

>How do you suggest to deal with PON calls? I wonder if I need to remove them and consider PASS only.

Their filter is not `PASS` should they should be ignored - GRIPSS considers them non-somatic events.

> Is there a reason why "PON" is included in final gripss.somatic.filtered.vcf.gz?

The Hartwig pipeline clinical pipeline includes logic to whitelist known driver events regardless of their PON status. That is, variants flagged as PON have their PON status removed downstream of GRIPSS (hence why GRIPSS uses `FILTER` instead of actually removing the events).
