### ISSUE TITLE
High-confidence normal/germline SV filtering

### ISSUE THREAD

**Issue by tgong1** [PapenfussLab/gridss#590]
Hi Daniel,

I have a further question to filter high-confidence germline SVs, which is related to my previous question submitted #374.

GRIDSS SV calling was ran on a pair of matched tumour and normal. I was trying to obtain germline SVs by extracting high confidence SVs in the normal, using the following commands in R. I really want to make sure I'm doing it properly.
vcf <- vcf[vcf@fixed$QUAL >= 500,]
vcf <- vcf[VariantAnnotation::geno(vcf)$QUAL[,2] < 0.05 * vcf@fixed$QUAL,]###normal is the first INPUT, tumor is the second INPUT

By looking at the resulted VCF, I found some results which I'm not sure if they are supposed to see. The following example SV has QUAL score of 2537.34, however, both QUAL for normal and tumour are 0. Is this supposed to see? What does QUAL of 0 mean?

chr1 99117 gridss0f_314b G GACAGTGTAAAAAACTTTCACCTGGGGTGGAGTGCATTGTGGGAAACACGACTAACTGCAAATTATGCCACCCAGGTTAAAGTGATTAGACAGCCAAAGCCCCCCAAGGAGGGGGG. 2537.34 PASS AS=0;ASC=1X;ASQ=0.00;ASRP=0;ASSR=0;BA=4;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=578.15;BASRP=3;BASSR=21;BEID=asm0-604,asm0-613,asm0-620,asm0-636;BEIDH=-1,-1,-1,-1;BEIDL=0,0,0,0;BQ=2537.34;BSC=80;BSCQ=1833.86;BUM=5;BUMQ=125.32;BVF=82;CAS=0;CASQ=0.00;CQ=1111.17;EVENT=gridss0f_314;IC=0;IQ=0.00;RAS=0;RASQ=0.00;REF=255;REFPAIR=255;RP=0;RPQ=0.00;SB=1.0;SC=1X;SR=0;SRQ=0.00;SVTYPE=BND;VF=0 GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF .:0.00:0:0:0:0.00:0:0.00:184.12:0:8:753.87:24:541.43:1:28.32:24:0.00:0:0.00:0.00:0.00:67:76:0:0.00:0:0.00:0 .:0.00:0:0:0:0.00:0:0.00:394.03:3:13:1783.46:56:1292.43:4:97.00:58:0.00:0:0.00:0.00:0.00:188:179:0:0.00:0:0.00:0

Thank you for your time and help!
Tingting

**Comment by d-cameron** [comment]
> What does QUAL of 0 mean?

The QUAL field is the overall variant score. For breakpoints this matches the `FORMAT` `QUAL` fields but for single breakend, it's the `FORMAT` `BQ` field. That is:

`FORMAT` `QUAL`: per sample break*point* support (split reads, discordant read pairs, breakpoint assemblies)
`FORMAT` `BQ`: per sample break*end* support (soft clipped reads, reads with unmapped mates, breakend assemblies)

Breakpoint will typically have non-zero `FORMAT` `QUAL` and `BQ` (since reads spanning the breakpoint by less then ~25bp will be aligned as soft-clipped reads, not split reads) but the overall `QUAL` score for breakpoints is determined only from the breakpoint support (not the breakend `BQ` support).

Breakends will always have zero `FORMAT` `QUAL`.
