### ISSUE TITLE
Short insert size

### ISSUE THREAD

**Issue by oghzzang** [PapenfussLab/gridss#624]
My data was obtained from very old FFPE samples. 
So, their insert size is 120 bp.. but we performed 151 bp paired-end sequencing. So our paired end reads are composed of overlapping paired reads.

1. If there are truly structural variants in my data, would it be possible to call them using evidence from split reads?

2. And if a structural variation is observed in an overlapping read pair, does "gridss" annotate the number of split reads as 2 in the VCF or 1?

3. Do I have to clip the overlap reads to use your tool?

Many Thanks.!

**Comment by d-cameron** [comment]
> If there are truly structural variants in my data, would it be possible to call them using evidence from split reads?

Yes, but your signal strength will be significantly lower than a library with 600bp fragments.

Also note that FFPE samples have a lot of artifacts in them so not only will your signal be weaker, your noise will be higher.

> "gridss" annotate the number of split reads as 2 in the VCF or 1?

The `SR` split read count will be 2 (since there's two split reads), but the `VF` contribution will be 1 as it's just a single fragment supporting the variant. `VF` handle both 2*SR support as well as `SR`+`DP` fragments.

> Do I have to clip the overlap reads to use your tool?

GRIDSS performs adapter trimming so if you used one the of the standard adapters (https://github.com/PapenfussLab/gridss/blob/master/src/main/resources/gridss.properties#L17) then no, clipping is not required.

**Comment by oghzzang** [comment]
Thank you very much!! However, my question #3 is not about adapter trimming. My data has extensive overlaps like this. My question is whether I need to remove this overlap before using Gridss.

ex. read trimming (151 bp ➞ 50bp) ➞ mapping 

 ![ image](https://user-images.githubusercontent.com/33537478/229727812-146a9c03-93c7-4741-8c4f-2c9ad2649fce.png)

**Comment by d-cameron** [comment]
Those fragments are fine. It's only an issue if adapters aren't trimmed and
you use a nonstandard adapter. It is only in such cases where there is more
than 5bp of 'dovetail' soft clipping that gridss considers the reads to
provide SV support. If it's just R1 and R2 overlapping then there's support
for an SV.

**Comment by oghzzang** [comment]
Many thanks.!!!!!!!
You save my life!
