### ISSUE TITLE
gridss for long-read data?

### ISSUE THREAD

**Issue by kerstinth** [PapenfussLab/gridss#636]
Hi,

Out of curiosity - do you have any experience in running GRIDSS on long-read sequencing data? Or do you have any thoughts on whether this would work? 

Best wishes,
Kerstin

**Comment by d-cameron** [comment]
Gridss does not support long read data. This is due to a) the Gridss
assembler assuming an illumina-like error model and not handling indel
errors; b) the use of bwa mem for split read & assembly alignment (not a
critical blocker as the assembler can be swapped out for a different one);
and c) memory usage optimised for short reads (so Mb length ONT reads would
cause a large % of the input bam to be loaded and cause out of memory
errors.

It might work with error-corrected pacbio hifi reads but I don't expect it
to outperform a proper long read sv caller such as sniffles.

**Comment by kerstinth** [comment]
Thanks very much for explaining this - that's great to know!
