### ISSUE TITLE
How many open files error

### ISSUE THREAD

**Issue by iprada** [PapenfussLab/gridss#70]
Hi!

I am using gridss in a HPC cluster with mutiple threads and I am running in the known problem of too many open files. Is there way of knowing aproximately how many -ulimit would I need in order to contact the system administrator and ask them to increase it?

I think that it would be great to know that aproximate number for 8 threads, and 16 threads given that one is using the canonical reference genome.

thanks!

**Comment by lparsons** [comment]
It's possible this is related to https://github.com/PapenfussLab/socrates/issues/2

**Comment by iprada** [comment]
Updating to the last version solved the issue.

The update was from 1.3.2 to 1.3.4

**Comment by d-cameron** [comment]
Great to hear (sorry about the lack of response - I was travelling to present GRIDSS at NGS 2017).

Actively used file handles should peak at 4 * #threads * #input files. Actual usage will be higher as some handles are not released until a java GC. There was also a file handle leak that I fixed in GRIDSS 1.3.4.
