### ISSUE TITLE
no GT information

### ISSUE THREAD

**Issue by yeswzc** [PapenfussLab/gridss#73]
Hi, I've run GRIDSS for 400 plants. But the GT columns are all "." in the output vcf file.
GRIDSS do not do genotyping ? Or what is wrong?

The output is like:
GT:ASQ:ASRP:ASSR:BAQ:BQ:BSC:BSCQ:BUM:BUMQ:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ
.:0.00:0:0:0.00:0.00:0:0.00:0:0.00:0.00:0:0.00:0.00:0.00:0:0:0:0.00:0:0.00      .:0.00:0:0:0.00:0.00:0:0.00:0:0.00:0.00:0:0.00:0.00:0.00:0:0:0:0.00:0:0.00
...

The command line I use was:
java -ea -Xmx250g  -Dsamjdk.create_index=true -Dsamjdk.use_async_io_read_samtools=true -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=true -Dsamjdk.compression_level=1 -cp ~/bin/gridss-1.3.4-jar-with-dependencies.jar gridss.CallVariants TMP_DIR=. WORKING_DIR=. REFERENCE_SEQUENCE=~/01.reference/IRGSP-1.0/IRGSP-1.0_genome.fa INPUT=1.bam INPUT=2.BAM ... OUTPUT=gridss/01.GRIDSS.run400.vcf  
ASSEMBLY=gridss/01.GRIDSS.run450.assembly.bam

PS:
I didnot successfully test the test data, it failed because of :
"Caused by: htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequence dictionaries are not the same size (84, 25)". Maybe it is because of wrong reference genome, So I ignored it.

**Comment by d-cameron** [comment]
GRIDSS does  not perform genotyping. The GT column is only written because it is required to be compliant with the VCF specifications. That said GRIDSS does output the key information required to infer a genotype:
- `REF` and `REFPAIR` can be used to determine if a break-end is heterogeneous or homozygous
- Variant allele frequencies can be approximated using `readVAF=(IC+SR)/(IC+SR+REF)` and `pairVAR=RP/(RP+REFPAIR)`

Note that a breakpoint can be homozygous at one break-end but heterogeneous at the other (e.g. inter-chromosomal translocation combined with lost all non-variant copies of one of the chromosomes involved).

**Comment by d-cameron** [comment]
>I didnot successfully test the test data, it failed because of : "Caused by: htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequence dictionaries are not the same size (84, 25)". Maybe it is because of wrong reference genome, So I ignored it.

You are correct. The reference genome used by GRIDSS must have the same chromosomes in the same order as the reference genome used to perform alignment.

**Comment by yeswzc** [comment]
Thank you very much !

**Comment by DarioS** [comment]
I am reading the definitions of the INFO fields and wonder if the use "breakpoint" in REFPAIR should be "breakend" instead.

```
##FORMAT=<ID=REF,Number=1,Type=Integer,Description="Count of reads mapping across this breakend">
##FORMAT=<ID=REFPAIR,Number=1,Type=Integer,Description="Count of reference read pairs spanning this breakpoint supporting the reference allele">
```

If a read pair spans the breakpoint then it wouldn't support the reference sequence but if they're placed immediately on either side of the breakend, it would support the reference. The definition of REF is also ambiguous. Does  "Count of reads" mean that paired-end sequencing reads are double-counted if the DNA fragment is short and the reads both overlap the breakend? This would only apply to a tiny minority or read pairs but it's good to know in case some region of the genome fragment much more easily than typical and is enriched for short fragments.

I wonder if StructuralVariantAnnotation provides such genotyping and variant frequencies that were desired by Zichao? I saw "variant allele fractions" mentioned in the software vignette, but wasn't sure if any of the functions calculate it.

**Comment by d-cameron** [comment]
`REFPAIR` is calculated from the inner alignment extents of the read alignments, `REF` requires an alignment to span across the breakpoint position. This approach prevents any double-counting of reference-supporting reads.

It even more complicated when there is a non-trivial micro-homology length (e.g 50bp). GRIDSS reports the reference support based on the minimum support across the homology interval (typically this is one of the two extreme of the homology interval). There is a systemic bias in the read alignments over the homology interval (reads spanning the homology will the aligned to the side that has the most non-homologous read bases) so half the reads will align to one side, and the other half to the other. The GRIDSS approach enables homozygous variant with micro-homology to correctly reported as homozygous, whereas a naive approach would call these as heterozygous.

> I wonder if StructuralVariantAnnotation provides such genotyping and variant frequencies that were desired by Zichao? I saw "variant allele fractions" mentioned in the software vignette, but wasn't sure if any of the functions calculate it.

In the general case, SVA can't do genotyping and VAF calculation because a) the standard VCF fields defined in the VCF specs are insufficient, and b) each caller uses their own custom attributes.

I use the following for GRIDSS VAF calculations:
https://github.com/hartwigmedical/scripts/blob/master/gridss/libgridss.R#L283

For variants under 1000bp, I don't used the read pair support as that will under-estimated VAF. Most read pairs spanning a 50bp deletion will still fall within the expected fragment size distribution so are (incorrectly) counted as `REFPAIR` and not `RP`. There's an RP-based caller that used a Gaussian mixture model to correct for this and I might incorporate that approach in a future release of GRIDSS but for now, they're just counted as `REFPAIR` because they fall within the bounds of the fragment size distribution.

**Comment by d-cameron** [comment]
> I am reading the definitions of the INFO fields and wonder if the use "breakpoint" in REFPAIR should be "breakend" instead.

It should. Wording will be fixed in the next release
