### ISSUE TITLE
Detected Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true. GRIDSS requires Java 1.8 or later

### ISSUE THREAD

**Issue by chirrie** [PapenfussLab/gridss#95]
I am getting this error when I ran the gridss simple analysis test script.
Java is installed on my system and I have set the path but I still get the error. Kindly give me a way forward...

Detected Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true. GRIDSS requires Java 1.8 or later

**Comment by d-cameron** [comment]
GRIDSS requires Java 1.8 (or later). The example script tests this by running `java -version` and checking for the string `1.8` in the first line. It appears the output from running `java -version` on your system is `Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true` instead of the expected `java version "1.8.0_131"`. Which JVM are you running? Can you paste the full output from running `java -version` on your system?

If you do indeed have java version 1.8 or later you can safely remove the java version check from the script.

**Comment by chirrie** [comment]
I am running java/1.8.

This is the java version details
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Comment by d-cameron** [comment]
I've updated the java version check in the example to handle the non-default `_JAVA_OPTIONS` you have defined on your system. In any case, you can safely remove the java version check from your script.
